### ISSUE TITLE
DNFDRAGORA 1.1.0 Location

### ISSUE THREAD

**Issue by Brushtail-Highton** [manatools/dnfdragora#100]
Looking at the changes file, it talks about the changes done for version 1.1.0, but when I download the zip file of source code and build it, running the built program and displaying the about information says the program is still 1.0.1. Where do I get the 1.1.0 program from?

**Comment by Conan-Kudo** [comment]
We haven't released it yet. It's planned to be released soon.

**Comment by carabao72** [comment]
hello, 

Have you news concerning the exit(release) of the version 1.1.x? 

Thank you very much for your work.

**Comment by anaselli** [comment]
New release [1.1.0](https://github.com/manatools/dnfdragora/releases/tag/1.1.0) has been tagged. Please contact fedora packagers.
