### ISSUE TITLE
Images in README.md are not accessible

### ISSUE THREAD

**Issue by abitrolly** [manatools/dnfdragora#103]
Examples at https://github.com/manatools/dnfdragora/blob/master/README.md are not opening.

**Comment by anaselli** [comment]
we need some new screenshot and link them into readme. Any helps?

**Comment by Conan-Kudo** [comment]
I'll take care of it. I already had made new images a while ago. I'm just lazy and terrible and haven't updated them.

**Comment by anaselli** [comment]
Thanks Neal, i just hoped in some external help for trivial issues ;)

**Comment by anaselli** [comment]
this should be closed now.
