### ISSUE TITLE
dnfdragora repeatedly creates new notifications

### ISSUE THREAD

**Issue by coreyfarrell** [manatools/dnfdragora#105]
Currently `dnfdragora/updater.py` uses `/usr/bin/notify-send` to produce desktop notifications.  This means that every morning I have a bunch notifications from dnfdragora since notify-send does not update the existing notification, it just keeps creating new ones.

It would be preferable to instead use python code handle notifications directly so the notification can just be updated instead of creating a new one.  This can be done with either:
```python
import notify2
```
  or
```python
import gi
gi.require_version('Notify', '0.7')
from gi.repositories import Notify
```

I'm willing to create a pull request for this but would first like to hear which module would be preferred.  `notify2` is not available as a package in Fedora, it claims to avoid GTK dependency but I'm not sure that matters for this?

https://notify2.readthedocs.io/en/latest/

**Comment by Conan-Kudo** [comment]
I'd prefer `notify2`, since we don't want a GTK+ dependency for people using it with Qt.

**Comment by coreyfarrell** [comment]
Sounds good to me.  For testing purposes I've used pip3 to install notify2 to my Fedora 28 laptop, I'm running a patched copy of dnfdragora-updater (I simply replaced dnfdragora/update.py in my system dir, deleted the associated __pycache__ files).  I can post a PR once I've verified this works as expected (in 3 hours it should show fewer updates available as I updated vim only).
