### ISSUE TITLE
Enhancement requests – Optimal use of the screen's surface.

### ISSUE THREAD

**Issue by Ricky-Tigg** [manatools/dnfdragora#107]
**OS**: Linux – Fedora 28 Desktop
**Current component**: dnfdragora.noarch 1.0.1-10.git20180108.b0e8a66.fc28

Since searches targeted to resources may produce consequent outputs an underlying optimization of the space used is needed. Following observations are related to that field:
– Ability to **expand** the _Dnfdragora_ window to **fully fill the screen** (_key F11_). To be tested on _Gnome_.
– **Icon illustrating application** –Dnfdragora– to be located on the **left top corner** (left side of '_File_').

![dnfdragora](https://user-images.githubusercontent.com/26058215/40172506-0644ca96-59cf-11e8-89a7-2ba2fea4bcf4.png)

– Ability to move **vertical separation bar** (here needed to the left).

![dnfdragora2](https://user-images.githubusercontent.com/26058215/40173191-4b9e759a-59d1-11e8-88f7-35824a637836.png)

– Ability to move **horizontal separation bar** (here needed up).

![dnfdragora3](https://user-images.githubusercontent.com/26058215/40173420-14463fc8-59d2-11e8-9f75-a6bdaa0416cc.png)

– Ability to optimize above mentioned both **vertical** and **horizontal separation bars' locations** by _double-left-clicking_ the bar involved. 
– **Optimization** of the use of space related to columns to be the **default behaviour.**  For now optimizations rely on manual operations –_double-left-clicks_– (See respective **double-arrow**).

![dnfdragora5](https://user-images.githubusercontent.com/26058215/40175553-c2a5e662-59d8-11e8-851a-c347ab54ed93.png)

Expression _in brackets_ –here  '_(7/7)_'– to be located on the **same line** as the **immediate previous line**.

![dnfdragora4](https://user-images.githubusercontent.com/26058215/40174423-506399e4-59d5-11e8-9cec-ba1f8ab63ab1.png)

**Comment by anaselli** [comment]
Well the only behaviour we could try to change from dnfdragora side is just the last one, that is an implementation choice to anyway avoid a behaviour related to libyui api. Others are all related to [libyui](https://github.com/libyui)

**Comment by Ricky-Tigg** [comment]
Test environment: **13.3-inched** screen laptop – **1280 x 800** pix resolution – **Cantarell Regular 11** interface font. Actuals results: **nine lines** are **visible** at once.. All optimisations would bring to visible at once about **12 new lines**.. Therefore _last enhancement_ as part of the whole is _1/12_,

**Comment by hrw** [comment]
I tried to use that tool on 1366x768px 11.6" laptop. Complete disaster. Feels like all developers use 4K+ screens.

**Comment by Conan-Kudo** [comment]
For what it's worth, I don't have a 4K screen. I use regular 1080p screens still.

**Comment by hrw** [comment]
I looked at libyui docs. It is good for ncurses apps. Nothing more. Ignores all UX/UI guidelines ever created. So @Ricky-Tigg forget that it will be better - libyui disallows it to be better.

**Comment by hellcp** [comment]
libyui would allow it to be better, but it certainly won't be with that attitude.

**Comment by hrw** [comment]
Reported https://github.com/libyui/libyui/issues/158 for start.

Let's see how they react.

**Comment by hellcp** [comment]
They don't respond to issues on Github, only openSUSE Bugzilla

**Comment by hellcp** [comment]
Also, I doubt you will get far by suggesting features, libyui for the upstream serves very specific purpose, and if there is no use for the widget for the upstream, they most likely won't bother. If you want to see changes in libyui, I suggest you contribute to it and create features you need in it.

**Comment by anaselli** [comment]
Removed logo line to gain room, new menubar from libyui-mga
![immagine](https://user-images.githubusercontent.com/1303486/89713708-c960a800-d999-11ea-96b1-ae30f3c09c8f.png)

![immagine](https://user-images.githubusercontent.com/1303486/89713733-f9a84680-d999-11ea-9c2d-aecf08bc953b.png)

**Comment by Ricky-Tigg** [comment]
I will use it; That should happen along with the up coming Fedora 33 release scheduled for October 2020.

**Comment by hrw** [comment]
Much nicer!
