### ISSUE TITLE
dnfdragora-updater 'box' icon no longer showns after webkitgtk4 update in fedora 27

### ISSUE THREAD

**Issue by MysteryGuy1** [manatools/dnfdragora#108]
I've been using dnfdragora and dnfdragora-updater on my Mate desktop on a Fedora 27 system. I normally have a dnfdragora 'box' icon displayed on the upper Mate panel (from which I can select 'Check for updates', etc.).

I recently updated webkitgtk4, and after this I no longer get the dnfdragora 'box' icon displayed on the upper Mate panel. I can manually open dnfdragora from the 'System/Administration' menu, and that appears to function normally.  

I updated from webkitgtk4-2.20.1-1.fc27.x86_64 to webkitgtk4-2.20.2-1.fc27.

Three packages actually got updated, 

   webkitgtk4
   webkitgtk4-jsc

and 

   webkitgtk4-plugin-process-gtk2

  I started here in case this is a known issue, since so far only dnfdragora has shown a behaviour change.

Thanks.

**Comment by anaselli** [comment]
Honestly i can't remember a dependency like that. Anyway I think you could check running dnfdragora-updater from console, maybe you can find something useful on output...

**Comment by Conan-Kudo** [comment]
dnfdragora doesn't use webkit at all...

**Comment by MysteryGuy1** [comment]
I'm not sure how it's related, just the net effect. One question I had is if anyone else has seen this, or if it's peculiar to my system.

I went back to a snapshot before the update, and you can see the box being shown on the Mate panel in w-box.jpg (along with a pop-up for the 3 pending updates).. 

![w-box](https://user-images.githubusercontent.com/39384009/40258236-e495f9a6-5abe-11e8-882a-64a3a40749bd.jpg)

After updating the 3 packages, the box is no longer shown. (I'm not exactly sure if this box always just appeared or if I had to do something to get it there in the first place.) Since there aren't currently any updates, I can't tell if the pop-up with available updates would have shown.

![wo-box](https://user-images.githubusercontent.com/39384009/40258259-fc0033b8-5abe-11e8-8eb7-69321d7aecd0.jpg)

I can see the python3 process is running for the updater

xxxxxxxx     1692  1568  0 213929 62984  1 17:12 tty2     00:00:00 python3 /usr/bin/dnfdragora-updater

Going back again to before the update, I logged in with 'Gnome classic', but I don't get the box. (I can't say if it was ever there in that environment or not).

Running dnfdragora-updater from the command line doesn't seem to be much different before or after the update. From before:

_dnfdragora-updater_

Skipped exception: <[Errno 2] No such file or directory: './dnfdragora.yaml'> 
icon /usr/share/icons/hicolor/128x128/apps/dnfdragora.png

(dnfdragora-updater:5275): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
shutdown
dnfdragora-updater _termination_

The 'shutdown' was from selecting exit.

From after:

_dnfdragora-updater_ 

Skipped exception: <[Errno 2] No such file or directory: './dnfdragora.yaml'> 
icon /usr/share/icons/hicolor/128x128/apps/dnfdragora.png"

**Comment by anaselli** [comment]
So it seems to be running. And yes, updater disappears as soon as it realizes there are not updates, and it could appear again after next check (configurable time, i seem to recall after 1 h)

**Comment by MysteryGuy1** [comment]
Ahh... my mistake then. 

I thought that the box icon was supposed to always be visible (so you could use it to open the dnfgradora UI when desired, or initiate a check  for updates from its mouse click menu) like the firewall icon. 

But, it appears that it is actually only displayed when 1 or more updates are available. Today there were 4 updates available. When I applied only the 3 wbkitgtk4 updates, I saw the box icon re-appear (after ending the dnfdragora installer UI)

Then, after applying the final update, the box icon does not appear any more. (Presumably because no more updates are available at that time).

I didn't find any preference to allow the box icon to always be displayed. Are there any configuration options that can be changed in a file somewhere that might allow this?

**Comment by anaselli** [comment]
dnfdragora is not single instance program, so running it twice can give rpm database problem (exclusive locking), most crashes were due to that, and i'm almost sure there was a bug in which someone asked to remove icon when no updates were present....

**Comment by MysteryGuy1** [comment]
I can see that people might want the icon to appear only when an update is currently available (to use as a signal that there currently are pending updates).

But, I also find it convenient to sometimes use the icon as a way to launch the main dnfdragora UI, etc. 

 So, as a suggestion, if you were to provide a preference to allow the icon to always be displayed I would probably use it. That is, presuming this didn't some how cause a problem. 

And it could default to the current behavior so as not to cause issues with current users.

 I could probably depend on the separate (short lived) pop-up you get after you first boot (when updates are available), or new updates become available as the signal that new updates can be applied. 

Also, the icon could (I assume) change color or appearance in some way to indicate when updates were actually available (as a more persistent indicator).

Just a thought, and not a big deal.

Thanks, and sorry for the misunderstanding on my part as to the actual cause of the behavior I was seeing.

**Comment by anaselli** [comment]
Nothing to be sorry for :) 
I can't promise anything, but maybe you could open a different and enhancement issue for that.
A way could be to have something from configuration file that enable that behaviour when it is, when ever it is, developed.
Meanwhile if you agree, i would close this one

**Comment by MysteryGuy1** [comment]
Thanks.
