### ISSUE TITLE
Ubuntu version

### ISSUE THREAD

**Issue by superbonaci** [manatools/dnfdragora#109]
Would like to have dnfdragora on ubuntu. Could be possible?

**Comment by anaselli** [comment]
Well from Technical point of view that is possible. I've already ported some perl manatools tools on debian for myself in past... But dnfdragora does not manage apt, so you should use dnf to make it working. Are you using dnf?

**Comment by Conan-Kudo** [comment]
DNF only manages RPM based distributions (it operates on top of RPM). RPM is not the package format for Debian, and even if it was, DNF is not available in Debian at all, which is a core requirement for dnfdaemon, which is what dnfdragora depends on to actually do things. :)

So sadly, unless Debian moves to RPM at some point, this is probably not going to happen.
