### ISSUE TITLE
just a question.. dnfsamba <- Manatools

### ISSUE THREAD

**Issue by blackcrack** [manatools/dnfdragora#111]
Hi Peoples,

i guess you know from where i am.. how ever, a dnfsamba could be very cool, in the view of setup-samba which it's gone since Fedora 25, it is maybe possible for create a dnfsamba like in d-tools ?
because this works wonderful and should also usable in other distros where manatools use.. i might maybe against the manatools in OMLx because the D-tools should stay and maybe reprogrammed and update in an other p-lang, which was do ..  but i must admit, the manatools be really pretty well so far .. would really good if be a dnfsamba also on it.
At OMLx , the urpmi and Draktools should be maintained , also if be reprogrammed in an other language
and a urpmi for rpm4 exist.. so the sourcecode, why not use this.. okey, this is the wrong place to write this.. a distro with a history should not mixed up.. and diluted with other/ foreign tools
because it be not hold at the type of the Distro .. how ever ../ thinking out loud \\...

Actually, I just started because of dnfsamba so, could be dnfsamba be an issue/internal project at the manatools ? would be really great because then have the Admins/Users of the Distro again a really well Gui for configuring Samba Server and the SambaUsers(copy from system with UID/GID{button}) with the Samba folders and the access to it.

best regards
Blacky

blackysgate.de/net

**Comment by Conan-Kudo** [comment]
I don't know if it'd actually be called dnfsamba. I guess what you're actually asking for is a manatools component to configure samba?

**Comment by Conan-Kudo** [comment]
This is also the wrong venue to ask about this, as this is dnfdragora, rather than the manatools project...

**Comment by blackcrack** [comment]
both right.. was only a concern that is placed on the table
 :)
