### ISSUE TITLE
dnfdragora-updater notification icon does not appear when updates are available

### ISSUE THREAD

**Issue by adatum** [manatools/dnfdragora#112]
After the first time being closed, dnfdragora notification icon never appears again when updates are available.

The dnfdragora box icon appears in the notification area of the taskbar (MATE) and a popup notification appears on updates, but only once after booting. If dnfdragora is launched and closed after installing updates, the icon never re-appears again, even if there are updates.

The dnfdragora-updater process is running.

Fedora 28
dnfdragora-updater version 1.0.1 release 10.git20180108.b0e8a66.fc28

**Comment by anaselli** [comment]
Have you checked the time to check for updates? I can't tell you the
configuration key name by now sorry

**Comment by adatum** [comment]
`/etc/dnfdragora/dnfdragora.yaml` contains the default `update_interval: 180`

**Comment by adatum** [comment]
I just noticed a popup notification appeared (for a few seconds) to inform of pending updates, but no notification (dnfdragora box) icon.

**Comment by anaselli** [comment]
Fixed in dnfdragora 2.0.0
