### ISSUE TITLE
Allowing the application to be started up with no task to be performed.

### ISSUE THREAD

**Issue by Ricky-Tigg** [manatools/dnfdragora#117]
OS: _Fedora_ – Component: dnfdragora.noarch  1.0.1-10.git20180108.b0e8a66.fc28

Feature request: Option _Show updates next startup_ suits as intended; though when it is **unchecked**, application **saves the current configuration related to packages management at exit**. That behavior then leads the application once started to automatically perform an operation according to that configuration. That **executed operation** may nevertheless **not be the one** user may want to perform first. Furthermore since, the **process** attached to that running operation may be **CPU-consuming**,  it cannot be interrupted; attempting to do so, may produce a system error.

![dnfdragora_v 1 0 1-10_options](https://user-images.githubusercontent.com/26058215/45812148-3ea43080-bccf-11e8-9825-cc45258209e0.png)

Relevant suggestion: **addition** of an **option** allowing the application to be started up with **no task** to be performed, assuming such feature is already implemented in _dnfdaemon_, as _dnfdragora_ relies on that one to perform.

**Comment by anaselli** [comment]
I think you misunderstood show updates at next start up option. That just means that at the next startup dnfdragora filters for updates, refreshing metadata, checking for updates  or caching packages are always performed. What should be hopefully better in dnfdragora 2.x is that is performed asynchronously (not completed yet for instance for comps).
If two users run dnfdragora (or dnfdragora-update) at the same time  only one can get db locked, other one waits, but it shouldn't crash now.
Moreover dnfdragora can always be terminated even during a dnfdaemon call, but in some cases of course dnfdaemon needs to finish its operations so until that time dnfdragora cannot get the db locked again.

If you agree i'll close this bug, fill free to open a new one and/or add comments
