### ISSUE TITLE
Change default focus field for --ncurses to update list

### ISSUE THREAD

**Issue by abitrolly** [manatools/dnfdragora#119]
This is how `dnfdragora` looks like in Fedora 28 with GNOME and Tilix terminal.

![image](https://user-images.githubusercontent.com/8781107/47416667-db4e6800-d77e-11e8-8c37-c838168959ed.png)

Putting colors issue aside - darker background color is needed - the focus is on `Search` button, not at search field. For me it makes sense to put focus into update list window.

**Comment by anaselli** [comment]
I think that should be moved to [libyui-ncurses](https://github.com/libyui/libyui-ncurses) even if i'm not sure it easy to focus on both search button and on text field in ncurses though since there is no mouse interaction there

**Comment by abitrolly** [comment]
No need to focus on search button. It is useless if text field is empty.

**Comment by anaselli** [comment]
that has ben a choice to allow people adding text on search and press return but seems to work only in qt

**Comment by abitrolly** [comment]
If I remember it right, Qt allows to bind a signal to event, such as pressing `Return` on search field could trigger `Search` event. What is `libyui` abstraction for this interaction?
