### ISSUE TITLE
dnfdragora has empty desktop icon

### ISSUE THREAD

**Issue by AsciiWolf** [manatools/dnfdragora#122]
dnfdragora seems to have no desktop icon on Fedora and is displayed as a generic "python3" application in the GNOME Shell dock. See the attached screenshot:

![dnfdragora icon](https://user-images.githubusercontent.com/2339930/48155436-46de1c80-e2cb-11e8-8cd1-1c400e5f2aba.png)

I am using the latest `dnfdragora-1.0.1-13.git20180108.b0e8a66` package on Fedora 29.

**Comment by anaselli** [comment]
same as issue #96
