### ISSUE TITLE
Misleading button text

### ISSUE THREAD

**Issue by Zsul87** [manatools/dnfdragora#125]
There is a 'Check all' button at the bottom which in fact selects all listed packages. It is translated to Hungarian as 'Összes ellenőrzése', which literally means check all, but not in the sense of selecting all items, but like inspecting all. The correct translation would be 'Összes kijelölése', that means 'Select all'.

Maybe 'Select all' would be better in English as well, as 'Check all' has two different meanings and it makes ambiguous for the translators. In Hungarian these two words has very distinct meanings and they can not be interchanged with each other.

**Comment by yurchor** [comment]
Yes, there were reports that this is ambiguous. But frankly, those who do not care of disambiguation (check the code or better test the translation in vivo) will find the way to create disambiguations anyway. ;)

@Zsul87 Can you join the team and fix the translations on Transifex? Many thanks in advance if you can. This can make the process much more streamlined.

https://www.transifex.com/MageiaLinux/teams/9361/hu/

**Comment by yurchor** [comment]
Fixed in d49bf89
