### ISSUE TITLE
Improving arrengment of "System options" inside "User perferences"

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#126]
![screenshot](https://user-images.githubusercontent.com/25375330/52048060-5d021e80-2542-11e9-81f9-240b67051462.png)

Hi. This issue opened on the behalf of issue #70 , as "Angelo Naselli" asked me for that.

 I received version 1.1.1
The issue not fixed completely but only partially !
Now I see 3 categories:

    System options
    Layout options
    Search options

The "Layout options" & "Search options" are both okay because the options under each of them are one bellow the other.
But, the "System options" are not okay ! They are as before, one beside other in the same horizontal line ! They should be one bellow other like this:
"Proceed without asking for conformation"
"Interval in minutes to check for updates"

**Comment by Nokia808** [comment]
@anaselli 
Does this fixed in version 2 series or not ?

**Comment by anaselli** [comment]
Layout is improved, don't think it's what you expect though. I left thiis open waitinh for a comment from 2.0.x running

**Comment by aureoud-fr85** [comment]
#154 There are some improvements here. This issue should be closed Resolved Fixed.

**Comment by anaselli** [comment]
well nothing that has been officially released yet :) but yes we can move the discussion to bug #154
