### ISSUE TITLE
"New updates notification" stop in version 1.1.1 on Fedora !

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#127]
Hi again. I'm on Fedora 28 X64 bit Cinnamon edition. I recently received version 1.1.1

Today, I launched my PC & after 4 hrs from it's use, I opened GUI of dnfdragora to use search option to see certain packages are they available to me from reposirories or not. But I was shocked when I saw 7 official Fedora packages for update without previous notification about their existence !

I go to "Options" | "User preferences" | 

I saw under "layout options", that "show update next start up" is unchecked. I conclude that this was the cause (please correct to me). So, I checked it. Then restart my PC, but error not resolved ! I repeat reboot for multiple times but no fix !

Before version 1.1.1, dnfdragora was being unable to notify about new updates from 3rd party external repositories such as RPMFusion, so that when their was update for vlc only it gave me no any notification about it. But now it seem that notification about new updates failed completely for all repositories !

Other note: dnfdragora updater icon is always appearing in Cinnamon panel since I received version 1.1.1

---------------------------------------
By the way, is "show update next start up" is for activation of notification about availability of new updates ? If yes, then I would like to suggest on you to change it into "show new updates' notification" so as to be more clear for user from current text which some what confused.

**Comment by anaselli** [comment]
"Show updates next startup" just open dnfdragora in updates view (starting from next startup). Updates should be announced by updater, if it ever started and worked... dnfdragora itself does not do anything to check for updates from time to time

**Comment by Nokia808** [comment]
@anaselli 

Okay, but why you closed the issue ?! Is dnfdragora-updater part of dnfdragora or not ? If not then when I have to post this bug ? Does dnfdragora-updater has special repository of GitHub ? If yes, then give me it's link.

**Comment by anaselli** [comment]
The reason why dnfdragora-update didn't tell you for any updates could be anything but not update it-self except if it has been crashed, but for that i need the evidence of the crash and a  BT.
If for any reasons it wasn't able to understand that updates were present, then the reason is to move to dnfdaemon, and it cache managing, but for that there is a bug somewhere already.

**Comment by Nokia808** [comment]
@anaselli 
I opened a bug about this in dnf daemon at:

https://github.com/manatools/dnfdaemon/issues/27

But it seem that dnfdaemon not maintained !

**Comment by anaselli** [comment]
dnfdaemon is maintained

**Comment by anaselli** [comment]
you could try a test case.

1. kill updater
2. open a console
3. run updater from console
4 look if there are any issues (suche as dead processes for instance) when check for updates.

**Comment by Nokia808** [comment]
I did what you command me. Please see my replay at:
https://github.com/manatools/dnfdragora/issues/130

it is as following:

    1. right click on updater icon then click exit,
    2. opened terminal,
    3. run:

       dnfdragora-updater
       the updater launched & it's icon re-appeared in panel of DE. but I had the following error output in terminal:

$ dnfdragora-updater
Skipped exception: <[Errno 2] No such file or directory: './dnfdragora.yaml'>
Icon: /usr/share/icons/hicolor/128x128/apps/dnfdragora.png

What this mean ? And is this the right way to kill updater & run it again from terminal ? If not please give me exact commands one by one.

**Comment by anaselli** [comment]
It means that all went ok... so There is anything wrong there
