### ISSUE TITLE
dnfdragora client error when accessing transaction history

### ISSUE THREAD

**Issue by adatum** [manatools/dnfdragora#131]
`dnfdragora` shows the following error whenever attempting to access a specific transaction history entry (Menu bar: Information -> History).

![dnfdaemon_error](https://user-images.githubusercontent.com/9773655/52909757-941f4200-325b-11e9-9a3e-dd376f7f4916.png)

Clicking OK closes the dialog box and `dnfdragora` quits.

The specific transaction was when upgrading from Fedora 28 to Fedora 29.

What should I check? Did the entry get corrupted, or was there an issue during the upgrade?

**Comment by Conan-Kudo** [comment]
@adatum This is unfortunately a known issue that occasionally happens during the upgrade from Fedora 28 to Fedora 29, and not related to dnfdragora. See [RH#1600917](https://bugzilla.redhat.com/show_bug.cgi?id=1600917) for details.
