### ISSUE TITLE
Blurry updater tray icon in Plasma 5

### ISSUE THREAD

**Issue by vinzv** [manatools/dnfdragora#139]
The tray icon of dnfdragora-update is blurry in Plasma 5 (OpenMandriva Lx 4), see screenshot:
![Screenshot_20190624_224134](https://user-images.githubusercontent.com/74432/60051885-4e282e00-96d4-11e9-812e-5eedf9c53d55.png)

I tried to fix it manually and dug through the source, both without any luck. Can you fix that or tell me where to look at?

**Comment by Conan-Kudo** [comment]
This is where that code is:

https://github.com/manatools/dnfdragora/blob/56006a7c6e3d73db4fe0ccfc28bcae27d810d37d/dnfdragora/updater.py#L60-L73

The issue is that we don't send a vector icon, only a raster one. Unfortunately, our toolkit currently doesn't support vector icons. 😞 

This is an issue with libyui, and needs to be fixed there: https://github.com/libyui/libyui/issues/126

**Comment by blackcrack** [comment]
hmm..
https://www.pling.com/p/1254749/

therewith be you in possible move a 256x256 png in a svg/svgz
and have a clean, sharp icon who be in able for a nice scaling ..

i have make it with my whole iconthemes 
https://www.pling.com/u/blackcrack/
with the script : https://www.pling.com/p/1224130/

**Comment by anaselli** [comment]
Irc in updater i changed that... if you use an svg file is converted to png...

**Comment by vinzv** [comment]
@anaselli I saw some code doing that [here](https://github.com/manatools/dnfdragora/blob/master/dnfdragora/updater.py#L99). Yet I don't think it works. Forcing another icon path to svg files still loads the 128px png:

```
$ dnfdragora-updater --icon-path /usr/share/icons/hicolor/scalable/apps/
Skipped exception: <[Errno 2] Datei oder Verzeichnis nicht gefunden: './dnfdragora.yaml'> 
Icon: /usr/share/icons/hicolor/128x128/apps/dnfdragora.png
```

The same happens with directly pointing to the svg file. Both ways the tray icon stays blurry.

**Comment by anaselli** [comment]
As far as i can say it should load the theme one or the default if not present but i see it is a 128 pixels icon anyway as you can see [here](https://github.com/manatools/dnfdragora/issues/139#L95)

**Comment by vinzv** [comment]
Tried forcing 256px version, same result:
```
dnfdragora-updater --icon-path /usr/share/icons/hicolor/256x256/apps/dnfdragora.png 
Skipped exception: <[Errno 2] Datei oder Verzeichnis nicht gefunden: './dnfdragora.yaml'> 
Icon: /usr/share/icons/hicolor/128x128/apps/dnfdragora.png
```
I also copied the 256px png to some different location to make sure it's no path issue. But the result was exact the same.

**Comment by anaselli** [comment]
I'm not sure but i think /usr/share/icons/hicolor/128x128/apps/dnfdragora.png is your theme icon- And you should  change 256 into code
https://github.com/manatools/dnfdragora/issues/139#L95
and of course having a 256 theme icon.
For some reasons i can't remember now - a previous bug maybe- theme icon wins so option icon-path doesn't

**Comment by anaselli** [comment]
please try this [patch](https://gist.github.com/anaselli/b71da5ec2376efb5999f2e3d16b2e676) and tell me if it works.

**Comment by vinzv** [comment]
I applied the patch and now I can at least force the use of a different path. Nevertheless, the icon stays blurred.
I tried various sizes and even completely different icons but without any luck. :-(

**Comment by anaselli** [comment]
i don't think our 256x256 icon is so nice... maybe you should try something better (fedora should have changed our icons iirc), contributes are also welcome :D

**Comment by vinzv** [comment]
I can try to make something, but that won't solve this issue. See this quick try:
![Screenshot_20190626_230210](https://user-images.githubusercontent.com/74432/60214816-8d868400-9866-11e9-9af6-1fb8938a809b.png)

The PNG has 256x256 px at 96dpi and still gets blurred. I assume the conversion done in Python messes it up somehow.

**Comment by anaselli** [comment]
Well that icon is from a contributor, I'm not a graphic designer so I probably won't be able to do a good job there anyway. But I am ready to release any better solution from contributors

**Comment by anaselli** [comment]
Could you please new icons added by @pontaoski
