### ISSUE TITLE
Gtk-WARNING **: Allocating size to YGtkAdjSize without calling gtk_widget_get_preferred_width/height()

### ISSUE THREAD

**Issue by vstoykov** [manatools/dnfdragora#14]
This is a warning in the console. Probably is error in `libYui` but but I just wanted to mention it.
```
(python3:29016): Gtk-WARNING **: Allocating size to YGtkAdjSize 0x5615e438a4e0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```
I'm running Fedora 25.

**Comment by anaselli** [comment]
There are unfortunately warnings due to the upstream [libyui-gtk](https://github.com/libyui/libyui-gtk) it should be moved this bug there

**Comment by anaselli** [comment]
The issue has been addressed to libyui-gtk, reference to this bug is also there
