### ISSUE TITLE
Version for CentOS8

### ISSUE THREAD

**Issue by eldiener** [manatools/dnfdragora#141]
Can dnfdragora be built in CentOS8 ?

The recently released CentOS8 has no graphical package manager aside from the dreadful Software application which has no functionality to show/find anything about low-level dnf packlages.

**Comment by anaselli** [comment]
Dnfdragora itself should be since it is written in python 3. You need libyui and dnf-daemon too thoug

**Comment by Conan-Kudo** [comment]
It would be possible, yes. I don't know if @besser82 is interested in bringing it to EL8 though...

**Comment by eldiener** [comment]
What do you mean by "Ask to centos packages for this please." ? Do you mean asking on the CentOS8 forum if someone can create libyui and dnfdaemon packages ? I have tried to get others who use CentOS8 interested in the fact that it has initially been released without a GUI package manager, even in its normally popular 3rd party repositories ( EPEL etc. ) but so far the responses are to the effect of either "use dnf from the command line" or "it's still early so maybe this will happen in the future". That is why I am interested if anyone know if dnfdragora and its dependencies can be built in CentOS8.

**Comment by Conan-Kudo** [comment]
@eldiener basically, ask @besser82 (the maintainer in Fedora) to package it in EPEL 8.

**Comment by eldiener** [comment]
> 
> 
> It would be possible, yes. I don't know if @besser82 is interested in bringing it to EL8 though...

Although I am a programmer and know Python well I am just an end-user when it comes to dnf and knowledge of it in Linux. I have used dnfdragora on Fedora 30 and while it has a few glitches it works fairly well. If it is possible to port it to CentOS8 that would be great. I can of course try to build its dependencies and then try to build it in CentOS8, but I was just wondering if anybody had done so already. If not I can experiment and see what the issues are as far as just building it is concerned.

**Comment by anaselli** [comment]
As python programmer you maybe help us :D Maybe following the dnfdragora-asynk branch...
As far as i can say for packaging you could try to read some basic rpm howtos and try to rebuild fedora SRPMS in your centos. It's a lot of time i'm not using it so i cannot help you in this.
I'm closing this issue since it isn't a dnfdragora one :)
