### ISSUE TITLE
Not keeping track of installed packages in Fedora 30

### ISSUE THREAD

**Issue by eldiener** [manatools/dnfdragora#142]
I do not know if this issue has been brought up yet. I am running Fedora 30 with dnfdragora 1.1.1. When I start dnfdragora it shows me the packages that can be updated. After selecting the updates and applying the selection, the packages get updated successfully. Now, however, if I search for a particular name among the installed packages, dnfdragora often does not show a corresponding package as being installed even though it is installed, and if I do the search among all packages dnfdragora shows the package but the check box which means that it is installed is not there for the package. The search does not necessarily have anything to do with any of the packages originally updated. It is as if once I update packages dnfdragora loses track of which packages have been installed and which have not. If I close dnfdragora and reopen it, then dnfdragora works properly again when I search for an installed package. I believe the same sort of confusion will occur when adding and deleting packages; dngdragora somehow loses track of which [ackages are installed and which are not as far as showing this to the end-user when he uses the search facility.

**Comment by anaselli** [comment]
Please check if the problem persists into 2.02. Thanks

**Comment by eldiener** [comment]
The problem has been solved in Fedora 32
