### ISSUE TITLE
Not sorting columns in Fedora 30

### ISSUE THREAD

**Issue by eldiener** [manatools/dnfdragora#143]
I am running dnfdragora 1.1.1 in Fedora 30. I notice I can click a column to change the sort order of packages being displayed, since there are up/down arrows for each column, but nothing happens when I do. Evidently the GUI design is to allow sorting based on any of the columns, but the sorting function does not work at all. Is it supposed to work, or is this functionality that was never implemented despite the arrows for each column ?

**Comment by anaselli** [comment]
As far as i can say it works but the  sorting way is demanded to [libyui](https://github.com/libyui) implementation.
Sorting by name ascending:
![Sorting by name before](https://user-images.githubusercontent.com/1303486/66873308-69cb8300-efa8-11e9-826c-10b0852f954c.png)
and descending:
![sorting by name after](https://user-images.githubusercontent.com/1303486/66873372-89fb4200-efa8-11e9-8859-ef48c8e381d5.png)

**Comment by eldiener** [comment]
The sorting is not working for me at all on Fedora 30. Are you sure you have tried this on Fedora 30 with the version of dndragora that is installed there ?

I do not know what you mean by:

"but the sorting way is demanded to libyui implementation".

I can see installations of libyui, libyui-gtk, libyui-ncurses, and libyui-qt.

**Comment by anaselli** [comment]
Well no, i'm not on Fedora, but i do hope it isn't a distro matter. And [libyui](https://github.com/libyui/libyui) (look at the links) is the UI  abstraction we used.

**Comment by eldiener** [comment]
Let me assure you that on Fedora 30 none of the sorting on columns works at all for me. I did not see any option about turning sorting on columns on or off so I assume it should work. Of course it could theoretically be a hardware issue on my computer, but normally such functionality is not. If you can, and have Fedora 30 installed on your computer, would you please try it there, using the dnfdragora that is part of the Fedora 30 repositories. It is of course possible that the issue is fixed in some later build for dnfdragora, but I can only reflect what I see in Fedora 30.

**Comment by anaselli** [comment]
Just ot of curiosity, which version of libyui, libyui-qt and/or libyui-grk are you using in fedora 30?

**Comment by g6avk** [comment]
Sorting works fine here on F30, Plasma DE. 
Versions on this box:
libyui-3.3.3-5.fc30.x86_64, libyui-qt-2.47.1-14.fc30.x86_64, libyui-gtk-2.44.9-12.fc30.x86_64

**Comment by eldiener** [comment]
> Just ot of curiosity, which version of libyui, libyui-qt and/or libyui-grk are you using in fedora 30?

I am using libyui-3.3.3, libyui-gtk-2.44.9, libyui-ncurses-2.48.3, and libyui-qt-2.47.1. 

I also realized  that, although I choose Gnome and not Gnome-Xorg when logging in, I am not running Wayland because I am using NVidia 430.40 proprietary drivers from the rpmfusion-nonfree-nvidia-driver repostory for my GeForce GTX-960 Graphics Card. When I originally used the built-in npuveau drivers for my graphica card the Fedora 30 Gnome desktop would freeze every now and then. After switching to the NVidia drivers the intermittent freezes hjav stopped completely. Maybe dnfdragora works properly under Wayland as far as the sort order is concerned but since I am not running Wayland the columns do not sort for me.

**Comment by anaselli** [comment]
Just run it from a console/terminal as dnfdragora --qt for Qt or --gtk for GTK so you can be sure on which is running and look if both work properly or not

**Comment by eldiener** [comment]
Running 'dnfdragora --qt' the column sorting works. while running 'dnfdragora --gtk' the column sorting does not work. The actual command in the launcher is just 'dnfdragora'. When I changed the launcher to run 'dnfdragora --qt', it starts as before but now the sorting always works. Thanks very much for your help ! I have no idea why the '--gtk' version does not work correctly under Fedora 30.

**Comment by anaselli** [comment]
So it seems a libyui gtk issue

**Comment by eldiener** [comment]
I guess so. Maybe it also has something to do with not running Wayland on Fedora. I do not know enough about Waylanad to know what is affected by it or not. I will bring this issue up on the Fedora forum. Thanks for your help in resolving this for me.
