### ISSUE TITLE
Handle available architectures better

### ISSUE THREAD

**Issue by hrw** [manatools/dnfdragora#144]
Fedora/x86_64 has i686 architecture enabled for multilib packages. dnfdragora lists x86_64 and i686 packages in same lists. And by default 'architecture' column is off the screen which makes it easy to select wrong one.

There should be a better way for handling it.

**Comment by anaselli** [comment]
What do you suggest, to move the summary after arch?
So something like

|Name|Version|Release|Arch|Summary|Size
|---|---|---|---|---|---

Anyway there is the availability to show only x86_64 package though

**Comment by hrw** [comment]
"show x86_64 and noarch only" lists only notinstalled packages.

But yes, with not movable split between lists is is hard to improve it.

Can you consider dropping left list or moving it above list as combobox?

**Comment by anaselli** [comment]
> "show x86_64 and noarch only" lists only notinstalled packages.
hmm no, it shows all packages, so either installed or not.
![dnfdragora-x86_64_noarc](https://user-images.githubusercontent.com/1303486/71933191-d7e7a680-31a1-11ea-8dfb-67c0b26c7147.png)

**Comment by anaselli** [comment]
> Can you consider dropping left list or moving it above list as combobox?

I would say no, moreover combobox is flat, whil groups is a treeview, i will try to give it less room maybe

**Comment by hrw** [comment]
Looks much better.

**Comment by anaselli** [comment]
Would you mind testing our [dnfdragora-async branch](https://github.com/manatools/dnfdragora/tree/dnfdragora-async). Even if not completed, i need to understand if i can start managing merge to master.... any feed backs are welcome :)

**Comment by hrw** [comment]
Will have to sit and figure out how to get your code installed from git checkout. Last time I have tried instructions from readme file but failed.

Simple 'pip install .' would be great ;D

**Comment by anaselli** [comment]
I always follow those instructions 🤔 maybe I have something in the system that you have not and it's missing in README. Could you open a different issues for that please, and/or join us into #dndragora IRC channel?
pip was removed early because we needed some stronger checks, even if I can't remember now exactly.

**Comment by hrw** [comment]
Ok, did something wrong in past - worked this time.

Which irc network? Tried Freenode, Oftc, IRCnet.

**Comment by anaselli** [comment]
Sorry i was wrong the freenode channel is #manatools

**Comment by Conan-Kudo** [comment]
The async code has been merged into master, so test from there, please. :)

**Comment by anaselli** [comment]
With the async implementation i should have improved a bit what you asked for. I'll close this issue. Feel free to open a new one if you experience any problems
