### ISSUE TITLE
Dragora-updater works badly.

### ISSUE THREAD

**Issue by sale349** [manatools/dnfdragora#150]
My O.S. it's Fedora-Mate 32, the version of dnfdragora is 2.0.0. Up to Fedora31 the dnfdragora-updater icon was produced by the system, in the upper right panel, only when updates were available; once the updates were downloaded and installed, the icon disappeared. With Fedora 32 the icon appears even in the absence of updates and remains visible in the panel. It seems to me a wrong behavior: the presence of the icon in the absence of updates seems useless.

**Comment by anaselli** [comment]
You're right. I decided to leave icon active by now until pystray third party library gives to me a better behavior for that, i experienced too many crashes or in the better case that icon was not shown as soon as updates were ready.

**Comment by anaselli** [comment]
I changed icon when updates  are available for the moment. If i can trust menu trays to get a working hide/show menus i think i will add it as configurable so that user can decide if using as hidden with no updates...
Just to show is in WIP
