### ISSUE TITLE
F32 - dnf dragora crashed after updating repo

### ISSUE THREAD

**Issue by flotho** [manatools/dnfdragora#152]
Hi,

Freshly updated from F31 to F32 and my favorite dnfdragora is no more answering.
here are my latest logs :
``` <M> [mga-qt-ui] YMGA_QCBTable.cc:74 YMGA_QCBTable(): Slection mode 2
Get root backend. Locked (False)
Get root backend. Locked (False)
Unexpected error: <class ‘KeyError’>
<M> [ui] YUILoader.cc:163 deleteUI(): Shutting down UI
<M> [ew] YExternalWidgets.cc:116 ~YExternalWidgetsTerminator(): Shutting down mga External Widgets
<M> [ew] YMGAWidgetExtensionFactory.cc:49 ~YMGAWidgetFactory(): Factory removed
```

Any advice would be appreciated,

regards

**Comment by Conan-Kudo** [comment]
Try deleting `~/.config/dnfdragora*` and running `dnfdragora --exit` from the terminal, then start dnfdragora again normally.

**Comment by flotho** [comment]
Hi @Conan-Kudo , 

thanks for the time pent on my requets.

I tried as you proposed,

After the exit command :
```
method return time=1593283558.877154 sender=:1.945 -> destination=:1.944 serial=6 reply_serial=2
   boolean true
```
And now everything IS WORKING PERFECTLY!

Thansk a lot

**Comment by Hasshu** [comment]
@Conan-Kudo Apologies for hijacking this issue, but the question I have is somewhat on-topic: is there any reason why dnfdragora is still at v2.0.0 in the Fedora repos?
