### ISSUE TITLE
Reducing User preferences -window size according to the vertical axis compresses the formats

### ISSUE THREAD

**Issue by Ricky-Tigg** [manatools/dnfdragora#156]
**OS:** Fedora; **Component:** dnfdragora.noarch 2.0.0-2.fc32

Here is _User preferences_ window whose interface is with the default formats:

![dnfdragoa_user_preferences_1](https://user-images.githubusercontent.com/26058215/90246197-b9831100-de3c-11ea-8090-7ba5b2551959.png)

Here is the size reduced according to the vertical axis, which compresses progressively the formats:

![dnfdragoa_user_preferences_2](https://user-images.githubusercontent.com/26058215/90246869-24811780-de3e-11ea-8914-36af4e56eb6c.png)

**Comment by anaselli** [comment]
If you reduce the window i can't do anything in dnfdragora since that is how libyui works. Remember that it must work using gtk, qt and ncurses.
Said that now the dnfdragora option dialog has been reworked in the future release, we are waiting to fix a crash that came up with last updates.
