### ISSUE TITLE
notification declares that an update is available, opening dnfdragora shows no updates

### ISSUE THREAD

**Issue by ch604** [manatools/dnfdragora#158]
at latest patch (2.0.4-1.fc32), turning on my machine indicates from notifications that 1 update is available. but, opening the program from the system tray shows nothing to update.

i closed the window again, but received a new popup notification that an update was again available. refreshing metadata for dnf in the application still shows no packages to update.

after this happened a third time, i attempted an update from yum, which does show that google-chrome-stable is available as an update. this is not showing up for some reason in dnfdragora.

https://imgur.com/oEbMo8B.png - at initial opening of the application, after selecting 'update' from the system tray context menu.

https://imgur.com/qY84rh4.png - after searching for google-chrome, the update is now showing as available

https://imgur.com/nqe1pCq.png - when performing a yum update on the same system

**Comment by anaselli** [comment]
could you please test it with "All" view instead of "Groups" one?

**Comment by ch604** [comment]
if i go into the settings and disable the 'groups' view then restart the daemon, i am able to see the available update; ill leave this groups view off for now. 

https://imgur.com/BXnfjoy.png

additionally, i was not able to previously use the dropdowns where 'group' or 'all' are selected, but disabling groups reactivated this dropdown.

**Comment by anaselli** [comment]
Got it, thanks for the report. 
Some packages have not groups using comps as Fedora does. I will add an extra group for it.
