### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by mikebartnz** [manatools/dnfdragora#159]
In the last few days dnfdragora has ended up in an endless loop when trying to upgrade Teamviewer.
It goes "Build transaction" - "Applying changes to the system" endlessly.
Using Discover I find that the package is "GPG enabled: package not signed".
I realise that Teamviewer is nothing to do with you but the endless loop is. It took some digging to find the problem. 
Thank you for your time.

**Comment by anaselli** [comment]
Could you please provide the repo for teamviewer? I experinced and fixed something similar with skype and wrong gpg signature.

**Comment by anaselli** [comment]
tested on fedora rawhide and with teh version on master (2.1.0) is fixed as written into [Changes](https://github.com/manatools/dnfdragora/blob/master/Changes#L17)
