### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by besser82** [manatools/dnfdragora#16]
See:  https://bugzilla.redhat.com/show_bug.cgi?id=1436451

**Comment by anaselli** [comment]
Thanks @besser82 i'll look at it

**Comment by anaselli** [comment]
As i wrote it the original report, i cannot reproduce it atm. If someone can do it in vm, maybe saving a rollback position to test the case more times... or help me to find a way...

**Comment by besser82** [comment]
Looking at the (last comment in rhbz)[https://bugzilla.redhat.com/show_bug.cgi?id=1436451#c6] this might be related to the Gtk-backend…  It looks suspicious to me, there is the same backtrace in https://github.com/manatools/dnfdragora/issues/18#issuecomment-290253222.

**Comment by besser82** [comment]
Not an issue with dnfdragora-code, but libyui-gtk: (see rhbz)[https://bugzilla.redhat.com/show_bug.cgi?id=1436451#c9].

**Comment by besser82** [comment]
Temporary fix in https://github.com/manatools/dnfdragora/commit/cca941263476639fea617d664ed7e76cf220306a.

Leaving open to track…

**Comment by besser82** [comment]
Even fixing the GTK3-warnings in libyui-gtk (https://github.com/libyui/libyui-gtk/commit/3c7aad0b6edde4ba700b84518d3ff3a71bf27a6a) didn't fix this issue…  *sigh*  :(

**Comment by anaselli** [comment]
could you pleas test the following [patch](https://gist.github.com/anaselli/7a84baa6b7d53d733edcfee525feb904) to see if the crash still occurs? I tried this patch with the old dnfdragora without your max recursion changes and without libyui-gtk changes too, and it worked. I'll test with qt to see if we have no regressions there too

**Comment by besser82** [comment]
Test worked fine, when in a transaction with 1161 items (updating Fedora 25 Cinnamon Live with all recent updates available).

I used the unfixed libyui-gtk and removed the increase of recursion-depth in Python.

Thanks for fixing this issue.  =)

**Comment by besser82** [comment]
Fixed in https://github.com/manatools/dnfdragora/commit/0d6ff957131ee511ca896edbaa2550be421b0568.
