### ISSUE TITLE
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable

### ISSUE THREAD

**Issue by gorkoda1** [manatools/dnfdragora#160]
I was trying to figure out why dnfdragora's tray icon wasn't appearing in my taskbar (on MATE) so I enabled logging and got the following output on console
OS info:
Fedora 32 (MATE spin)
Python: 3.8.5
`
	Try reading configuration file

	From ./dnfdragora.yaml

	Finally read user settings from /home/censored/.config/dnfdragora.yaml

	Logging into /home/censored, debug mode is enabled

	Exception in thread Thread-1:

	Traceback (most recent call last):

	File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner

	self.run()

	File "/usr/lib64/python3.8/threading.py", line 870, in run

	self._target(*self._args, **self._kwargs)

	File "/usr/lib/python3.8/site-packages/dnfdragora/updater.py", line 302, in __update_loop

	self.__notifier.show()

	File "/usr/lib/python3.8/site-packages/notify2.py", line 222, in show

	nid = dbus_iface.Notify(appname,       # app_name       (spec names)

	File "/usr/lib64/python3.8/site-packages/dbus/proxies.py", line 72, in __call__

	return self._proxy_method(*args, **keywords)

	File "/usr/lib64/python3.8/site-packages/dbus/proxies.py", line 141, in __call__

	return self._connection.call_blocking(self._named_service,

	File "/usr/lib64/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking

	reply_message = self.send_message_with_reply_and_block(

	dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
`
It is notable that dnfdaemon is a service and not a socket on my system, so this could possilbly be the cause.

**Comment by anaselli** [comment]
Which version of pynotify are you using?

**Comment by gorkoda1** [comment]
sudo dnf info python3-notify2 outputs the following
Name         : python3-notify2
Version      : 0.3.1
Release      : 7.fc32
Architecture : noarch
Size         : 32 k
Source       : python-notify2-0.3.1-7.fc32.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Python interface to DBus notifications
URL          : https://bitbucket.org/takluyver/pynotify2
License      : BSD
Description  : This is a pure-python replacement for notify-python, using
             : python-dbus to communicate with the notifications server
             : directly.
             : 
             : It's compatible with Python 2 and 3, and its callbacks can work
             : with Gtk or Qt applications.

**Comment by anaselli** [comment]
Thanks but I was wrong, sorry I meant which version of pystray are you using? 
That's because new version use its internal notifier, and that seems make dnfdragora crashing (hopefully fixed on master). 
Thanks again for your report.

**Comment by anaselli** [comment]
I did a search and seems tha fedora 32 is shipping new 0.16.0. That is supported by next dnfdragora 2.1.0. So I suggest you to downgrade it to old 0.14.3 waiting for new dnfdragora that should be released very soon.

**Comment by gorkoda1** [comment]
OK thank you.

**Comment by anaselli** [comment]
As said this issue is fixed as written into [Changes](https://github.com/manatools/dnfdragora/blob/master/Changes#L4). 
Thanks for the report
