### ISSUE TITLE
Unexpected error: [Errno 20] Not a directory: '/usr/share/dnfdragora/images/dnfdragora.svg/dnfdragora-update.png' 

### ISSUE THREAD

**Issue by gorkoda1** [manatools/dnfdragora#168]
OS: Fedora 32 (Mate Spin)
dnfdragora version: 2.1.0
icon theme: Paper
this bug makes dnfdragora-updater unusable in certain conditions.
```
Try reading configuration file
From ./dnfdragora.yaml
Skipped exception: <[Errno 2] No such file or directory: './dnfdragora.yaml'> 
From /etc/dnfdragora/dnfdragora.yaml
Finally read user settings from /home/censored/.config/dnfdragora.yaml
Logging disabled
[Errno 20] Not a directory: '/usr/share/dnfdragora/images/dnfdragora.svg/dnfdragora-update.png'
Cannot open theme icon using default one /usr/share/dnfdragora/images/dnfdragora.svg/dnfdragora-update.png
Unexpected error: [Errno 20] Not a directory: '/usr/share/dnfdragora/images/dnfdragora.svg/dnfdragora-update.png' 
Closing dnfdragora-updater
```
This bug is likely caused by these lines.
```python
        if icon_path.endswith('/'):
            icon_path = icon_path + 'dnfdragora.svg' if ( os.path.exists(icon_path + 'dnfdragora.svg') ) else icon_path + 'dnfdragora.png'
        else:
            icon_path = icon_path + '/dnfdragora.svg' if ( os.path.exists(icon_path + '/dnfdragora.svg') ) else icon_path + '/dnfdragora.png'
```
https://github.com/manatools/dnfdragora/blob/92f9d550392678259f7092268cd2b368a01f13d9/dnfdragora/updater.py#L76

**Comment by anaselli** [comment]
Sorry could you please explain better which the problem is?
and why **/usr/share/dnfdragora/images/dnfdragora.svg/**?
is that a file? so it should not end with "/" 
is that a directory? then for some reasons  you don't have our icons there.

Anyway if you're suggesting that line is wrong, could you also be so kind to suggest how to fix it?

**Comment by anaselli** [comment]
I understood, second icon . Odd i haven't experienced it.... very odd.
Anyway to workaround it you could try to run it from terminal as

`dnfdragora-updater --icon-path /usr/share/dnfdragora/images/`

**Comment by gorkoda1** [comment]
> Sorry could you please explain better which the problem is?
> and why **/usr/share/dnfdragora/images/dnfdragora.svg/**?
> is that a file? so it should not end with "/"
> is that a directory? then for some reasons you don't have our icons there.
> 
> Anyway if you're suggesting that line is wrong, could you also be so kind to suggest how to fix it?

I actually have absolutelly no idea what's wrong with that 4 lines of code, but what I know is that if I print(icon_path) I would get the malformed path.

**Comment by gorkoda1** [comment]
OK I figured out what your fix did. Those lines did cause those errors but not in the way I thought.
Shouldn't those lines be deleted? I mean what's the point of checking dnfdragora.svg if dnfdragora is supposed to use dnfdragora-updater.svg?

**Comment by anaselli** [comment]
no i should get the path only once, but i left the old code right now to provide an easy patch for packagers.
Maybe we could do a bug fixing release soon...

**Comment by gorkoda1** [comment]
OK thank you.
