### ISSUE TITLE
Can you add "Update Notification" option, please ?

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#17]
Hi. I tried dnfdragora from copr repositories on Fedora 24 X64 bit Cinnamon version. I noticed that it have no "Update Notification" option as that existing in Yum extender (DNF).

In Yum extender (DNF) there is "performance" icon. By clicking this icon, a windows will open & contain many tab, one of them called "Update Checker" It give option to activate it or disable it, & give option to determain time interval by minutes at which Yum extender (DNF) check for availability of new updates, like every 60 minutes.

Kindly can you add this feature please ?

**Comment by anaselli** [comment]
Well dnfdragora idea comes from rpmdragora/rpmdrake so that is probably the main reason i didn't know that option in yumex-dnf :) I will take a look at the code and see how we could implement such a feature.. Thanks for using dnfdragora!

**Comment by besser82** [comment]
I'm already working on such a thing.  I'm trying to implement it using `pystray` which gives a pure-python abstraction for a tray icons using qtpy, appindicator, gtk+ or xlib.

Shouldn't take too long to get it done.

**Comment by Conan-Kudo** [comment]
@besser82 Awesome. That solves quite a lot of issues for us, too. :)

**Comment by anaselli** [comment]
@Nokia808 a WIP dnfdragora-updater has been pushed, if you want to try it and give us feedbacks...

**Comment by Nokia808** [comment]
@anaselli 
Hi. I installed dnfdragora-updater on Fedora 24 X64 bit Cinnamon edition. It is called "dnfdragora-gui". But how it work ?? I did not see any special option or setting to it after installing this package !!

Also, till now I did not see any notification about any update, though there are currently 3 update packages available !!

Please your kind help.

**Comment by Nokia808** [comment]
Hi. I upgraded my Fedora 24 to Fedora 26. 

On Fedora 26 dnfdragora-updater work O.K ! Today, it notify me that I have 42 update packages. Thank you.

But I did not examine further aspect of it. I use tty terminal to update/upgrade my system.
