### ISSUE TITLE
Ncurses front-end should not require X11

### ISSUE THREAD

**Issue by dnorthup-ums** [manatools/dnfdragora#173]
# Summary
The ncurses interface should not depend on being run in an X11 / XWayland virtual terminal.

# Expected behavior:
`dnfdragora --ncurses` (as root) or `sudo dnfdragora --ncurses` should just run the ncurses-based UI

# Actual behavior:
```bash
[dnorthup@hostname ~]$ sudo su -
[sudo] password for dnorthup: 
[root@hostname ~]# dnfdragora --ncurses
dnfdaemon client failure [g-io-error-quark: Cannot autolaunch D-Bus without X11 $DISPLAY (0)]
Try again using a login shell (i.e. "su -")
[root@hostname ~]# exit
logout
[dnorthup@hostname ~]$ sudo dnfdragora --ncurses
dnfdaemon client failure [g-io-error-quark: Cannot autolaunch D-Bus without X11 $DISPLAY (0)]
Try again using a login shell (i.e. "su -")
[dnorthup@hostname ~]$ uname -a
Linux hostname.tld 5.8.13-200.fc32.x86_64 #1 SMP Thu Oct 1 21:49:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

# Installed version:
```bash
[dnorthup@hostname ~]$ dnf info dnfdragora
Installed Packages
Name         : dnfdragora
Version      : 2.1.0
Release      : 2.fc32
Architecture : noarch
Size         : 1.6 M
Source       : dnfdragora-2.1.0-2.fc32.src.rpm
Repository   : @System
From repo    : updates
Summary      : DNF package-manager based on libYui abstraction
URL          : https://github.com/manatools/dnfdragora
License      : GPLv3+
Description  : dnfdragora is a DNF frontend, based on rpmdragora from Mageia
             : (originally rpmdrake) Perl code.
             : 
             : dnfdragora is written in Python 3 and uses libYui, the widget
             : abstraction library written by SUSE, so that it can be run
             : using Qt 5, GTK+ 3, or ncurses interfaces.
```
# Other
Did I forget anything that would be useful for debug?

**Comment by anaselli** [comment]
Could you please try the only command "su -" instead of running as sudo?

**Comment by dnorthup-ums** [comment]
@anaselli Same error, unfortunately.

As for a password UI, it wouldn't be a drop-in but there is GPG's pinentry.

**Comment by Conan-Kudo** [comment]
I'm pretty sure this is an issue with dbus-launch rather than us...

**Comment by anaselli** [comment]
if dbus-launch is installed you could try the command:
`$(dbus-launch) dnfdragora --ncurses`

**Comment by blackcrack** [comment]
a Asccii related surface could be cool ;) something with "display" , Menu, 2 frames for listing.. and possible to use over ssh as asccii surface for selecting different packages.. like "make config" from the kernel :smile_cat:

**Comment by anaselli** [comment]
@blackcrack dnfdragora works using ncurses for console already, though you need to be root and have dbus access.

**Comment by dnorthup-ums** [comment]
@anaselli That dbus incantation didn't work but this one does:
```bash
if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
    eval `dbus-launch --sh-syntax`
    echo "D-Bus per-session daemon address is:"
    echo "$DBUS_SESSION_BUS_ADDRESS"
fi;
dnfdragora --ncurses
```
(on Fedora 32).

Found that here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=690530#15

@Conan-Kudo Yeah, looks like dbus is the cranky one here. As Angelo noted, there's still the password-UI problem (I just ran it as root—I'm not going to encourage newbies to do that), but if that ends up having a separate ticket that's fine with me.

**Comment by anaselli** [comment]
Maybe someone should provide a ncurses ask password instead of a just tty one. But I don't know if that can be integrated in any ncurses applications well though. I even thought to write one in libyui, but I don't know how to start and never find the time to investigate it... i can't figure why we have a lot of people complaining for that and noone trying to work for a solution. Anyway this one is not a dnfdragora problem too...

**Comment by dnorthup-ums** [comment]
@anaselli Well, I have other things I could have complained about, but I try to restrict my comments to those I can stand a chance of being helpful fixing most of the time (unless I'm paying a vendor for support...). That's why I didn't comment on the password-UI up-front initially: I'm not currently up-to-speed on ncurses UI programming.

Anyway, I'm closing this, as the work-around noted above works and the root problem seems to be something in the D-BUS services interface layer (provided by that program and not this one).

**Comment by anaselli** [comment]
Fine, thanks. You can always open new issues, even if they are not directly addressed to dnfdragora,  sometimes that can help to find where they can be fixed, but certainly as this one can remain as help for other users. I'm one who does not think that issues are evil ;)
