### ISSUE TITLE
At present page's [<> Code] tab, some elements became obsolete

### ISSUE THREAD

**Issue by Ricky-Tigg** [manatools/dnfdragora#190]
**Tested on:** Fedora 34; **dnfdragora version:** 2.1.0

At present page's _<> Code_ tab, some elements became obsolete

- Snapshots of graphical interfaces – Qt and Gtk.
- Section _Installation_ 
  - dnfdragora packages maintained by Fedora: dnfdragora dnfdragora-updater.
  - Execution '`dnf -y install dnfdragora`' installs the GUI as well. 
  - **Dependencies Installed** along with above execution: comps-extras dnfdaemon libyui libyui-mga libyui-mga-ncurses libyui-ncurses python3-dnfdaemon python3-gettext python3-manatools python3-pyyaml python3-yui | **weak dependencies** | dnfdaemon-selinux libyui-gtk libyui-mga-gtk libyui-mga-qt libyui-qt libyui-qt-graph.

Don't have the knowledge about the packages maintained by Mageia.

**Comment by anaselli** [comment]
Sorry it isn't clear to me which the problem is... could you explain better?

**Comment by Ricky-Tigg** [comment]
No harm. Better to close.

**Comment by anaselli** [comment]
as you wish :)
