### ISSUE TITLE
window scaling in lower resolution monitor

### ISSUE THREAD

**Issue by Evan-aja** [manatools/dnfdragora#198]
**Description of problem**

    dnfdragora window extends beyond the screen limit and can't be resized to fit within the monitor

**Version-Release number of selected component**

    dnfdragora 2.1.0-3.fc34 
    Fedora 34

**How reproducible**

    Every time on 768p screen and lower (as tested)

**Steps to Reproduce**

    Open dnfdragora

**Actual results**

    Some GUI component is not accessible and the window cannot be resized nor maximized accordingly

**Expected results**

    Window can be maximized or resized on lower resolution screen

![image](https://user-images.githubusercontent.com/71018479/126019474-66ced8de-93fe-4caa-aab4-9b82343a4a91.png)

**Comment by anaselli** [comment]
Could please check if it is the same as issue #164?

**Comment by Evan-aja** [comment]
> Could please check if it is the same as issue #164?

yes, it is the same, recently i have found out that when using a "compact theme" fot the gtk app, in this case i use flat remix (doesn't matter which theme since they are all the same compact theme) and the scaling issue is somehow just fixed, like there are no other modification aside from the look and feel change of gtk, gnome shell theme and icons (all of which are flat remix in my case).

**Comment by anaselli** [comment]
Ok, this issue is addressed to libyui-gtk and concerning dnfdragora same as #164 please subscribe that one to be informed on progress. Thank you for reporting  it.
