### ISSUE TITLE
listing for mdbtools changed

### ISSUE THREAD

**Issue by DanielVillarreal** [manatools/dnfdragora#200]
Using Fedora 34 WS with dnfdragora
listing for mdbtools indicates 
repository: Fedora
https://github.com/brianb/mdbtools

You may want to edit this to reflect ...
https://github.com/mdbtools/mdbtools

I know it forwards automatically, but still ....

Thanks,
Daniel

**Comment by anaselli** [comment]
I'm afraid package information is not under dnfdragora control, it is retrieved from distribution db, so i think you should open an issue on fedora mdbtools package.

Thanks for using dnfdragora and reporting issues.

**Comment by DanielVillarreal** [comment]
Okay, Thanks for letting me know. Dnfdragora rocks.
