### ISSUE TITLE
Clicking to the right of a checkbox sets a remove flag even if the package isn't installed.

### ISSUE THREAD

**Issue by kah0922** [manatools/dnfdragora#203]
![image](https://user-images.githubusercontent.com/9474213/149249624-c9ee14d7-14ef-4984-beb9-44304cec73a6.png)
If you click to the right of a install box, it sets a remove flag. Accepting this change throws a transaction error.

System Info:
dnfdragora 2.1.0
Fedora 35 KDE

**Comment by anaselli** [comment]
nice catch! very odd behavior need to investigate.
