### ISSUE TITLE
dnf Dragora constantly crashes, does not even work in wayland.

### ISSUE THREAD

**Issue by dankmemermusic** [manatools/dnfdragora#205]
When you refresh it crashes, start it in wayland it crashes.
Specifics: when you click repositories then click cancel it crashes, then I click refresh repositories, I get this `Error occurred:
g-io-error-quark: GDBus.Error:org.baseurl.DnfSystem.LockedError: dnfdaemon is locked by another application (36)`

**Comment by anaselli** [comment]
The error you reported seems to say you cannot launch again dnfdragora after it was already up or crashed.
But that is the result not the issue itself, so please tell us what you did before it crashes (the very first time).

To lunch dnfdragora again after a crash, consider to run dnfdragora --exit first.

**Comment by dankmemermusic** [comment]
That problem is not there on 2.1.2. I was using 2.1.0
