### ISSUE TITLE
dnf dragora 2.1.2 won't maximize on gnome wayland on fedora 36

### ISSUE THREAD

**Issue by dankmemermusic** [manatools/dnfdragora#206]
Install f36 on a vm and then install dnf dragora then try to mazimize it. you can't maximize it and the bottom part won't show since you can't resize it to fit the screen.

**Comment by dankmemermusic** [comment]
vm screen size 1360 368. The same problem persists on cinanom too. 2.1.2 is way more stable than 2.1.0 so thats good. Yes I think I am using libyui-gtk. you can change horizontal size but you can't change vertical size. I have not tried this on real hardware though

**Comment by dankmemermusic** [comment]
I found this: https://github.com/libyui/libyui-gtk/issues/75

**Comment by dankmemermusic** [comment]
update: when I made the screen rez high enough to see the bottom, You can make it bigger and return it to its default but you can't make it smaller to fit the default screen res

**Comment by anaselli** [comment]
Unfortunately i was able to change only a little part of this issue (the -1 error reported [there](https://github.com/libyui/libyui-gtk/issues/75)) in libyui-gtk, but i haven't found where the resizing problem is. Finding a c++ test case could help maybe for debugging.

**Comment by dankmemermusic** [comment]
I've got an idea, mabey code it so it can be more compressed

**Comment by dankmemermusic** [comment]
or have it where you can resize the boxed areas on the interface

**Comment by anaselli** [comment]
> what is a c++ test case?
it is a libyui example written in c++ language that give the evidence of the problem. dnfdragora uses python language and that cannot help in "debugging" libyui-gtk.

> I've got an idea, mabey code it so it can be more compressed. have an option called compressed view
Feel free to try any solution you have in mind, code is into public repository, but please provide us a patch after so that we can merge it if it solves the problem :)

**Comment by dankmemermusic** [comment]
The problem is that I barley know anything about code since I'm not a developer. I think an easy way to fix this is just make it more compact mabey code it so it does not take as much space. I really just want it useable so I can click buttons like apply at the bottom. mabey the boxes where the entries, catagories and details are shown could just be coded to be smaller

**Comment by dankmemermusic** [comment]
work around is typing this into terminal `dnfdragora --qt` make sure you have qt installed for this. you can also make a shortcut for this too.

**Comment by anaselli** [comment]
> work around is typing this into terminal `dnfdragora --qt` make sure you have qt installed for this. you can also make a shortcut for this too.

if uninistall libyui-gtk and leave only libyui-qt it should start using qt b default

**Comment by dankmemermusic** [comment]
ok. 2.1.2 is a massive improvement over 2.1.0. way to go

**Comment by anaselli** [comment]
with the above libyui-gtk commit  and the https://github.com/manatools/dnfdragora/commit/f42fdf5aaf40aec34fc8ab86fdc6aeb3fd207518 this bug and should bi fixed
