### ISSUE TITLE
Dnfdragora backend's (dnfdeamon) ignores DNF's variables 

### ISSUE THREAD

**Issue by moceap** [manatools/dnfdragora#208]
Fedora remixes may have release number which doesn't match the Fedora one.

So, the new remix can't use any Fedora based repo!! Because releasever variable will read from os-release number which isn't match the Fedora ones.

Repo URLs contain Fedora's releasever.

To solve this issue we can use DNF variables, and set (releasever) variable to Fedora one, and making another variable for the remix release.

BUT, dnfdeamon ignores the dnf variables!

**Comment by moceap** [comment]
![dnfbug](https://user-images.githubusercontent.com/4345211/194441920-3792d2cd-c61b-40e3-a5e9-7f2c502111de.png)

**Comment by anaselli** [comment]
Thanks for reporting it, dnfdaemon patch has been merged

**Comment by moceap** [comment]
You're welcome, thank you too :)
