### ISSUE TITLE
The app is squashed when is opened

### ISSUE THREAD

**Issue by l-zacarias** [manatools/dnfdragora#216]
[Screencast from 2023-06-24 19-55-37.webm](https://github.com/manatools/dnfdragora/assets/108742284/656c50f1-aad9-423f-a318-48de1ddb8614)

The app is squashed when is opened, some users may think it doesn't work.
I have been able to replicate it on multiple devices
Running: Fedora 38 
Version: 2.1.2

**Comment by anaselli** [comment]
As far as i can say that should be a libyui-gtk problem. Please try dnfdragora-qt and see if it happens too. If no that is the only workaround I can suggest atm.

**Comment by Tuxman2** [comment]
Same problem for me too. :-(

**Comment by anaselli** [comment]
Please try libyui-qt  and tell me if  using "dnfdragora --qt" for instance the problem still persist

**Comment by Tuxman2** [comment]
The "dnfdragora --qt" option works. :-)

**Comment by anaselli** [comment]
> The "dnfdragora --qt" option works. :-)

that confirm that is a libyui-gtk issue. I had problem in updating my fedora VM last week end, hope to find some time next

**Comment by anaselli** [comment]
googling a bit i found that running export DISPLAY:0 before dnfdragora --gtk makes dnfdragora starting, even if the layout is not that good, but is bigger than a line to be enlarged.
As soon as i can i will investigate better if something on Gtk/Gdk APIs changed

Same as issue #227

**Comment by anaselli** [comment]
is there anyone here who can test a libyui-gtk patch to see if it solve this issue for him/her too?

**Comment by anaselli** [comment]
This issue should be fixed by [libyui-gtk 2.52.5](https://github.com/libyui/libyui-gtk/releases/tag/2.52.5).
