### ISSUE TITLE
Create an rpm package from dnfdragora sources ?

### ISSUE THREAD

**Issue by Tuxman2** [manatools/dnfdragora#218]
Hello,

is there a way to create an rpm package from dnfdragora sources ? For now, Fedora 38 has only dnfdragora 2.1.2 version. I would like the 2.1.4 version but it is not available for Fedora. So, is there a way to do what I want ?

Thanks.

**Comment by Conan-Kudo** [comment]
Update has been submitted to Fedora:

* F39: https://bodhi.fedoraproject.org/updates/FEDORA-2023-b2e34c3f6e
* F38: https://bodhi.fedoraproject.org/updates/FEDORA-2023-ce5decdc48
* F37: https://bodhi.fedoraproject.org/updates/FEDORA-2023-06efd2043a
