### ISSUE TITLE
Broken Matrix room link in README

### ISSUE THREAD

**Issue by sohang3112** [manatools/dnfdragora#219]
In *CONTRIBUTING* section of *README.md*, the link to manatools Matrix room is broken. Please fix the link.

**Current link:** https://matrix.to/#manatools:matrix.org

**Fixed link:** https://matrix.to/#/!manatools:matrix.org

**Comment by anaselli** [comment]
fixed with this [commit](https://github.com/manatools/dnfdragora/commit/ab9bea8f93b8ddec496fb76ecee79638c89ec5e2)
