### ISSUE TITLE
[GTK GUI] User Experience: How does the GUI work?

### ISSUE THREAD

**Issue by genodeftest** [manatools/dnfdragora#38]
I've been using yumex-dnf for a long time and I do not really understand how dnfdragora should work. Some issues:

Why are there dropdown menus on top left and top right? What does the "File" menu do?

What are the drowdown menus in the next line below for?

Why don't you use traditional menus or a GNOME-3ish look and feel with more buttons?

**Comment by anaselli** [comment]
File should have at least atm, 

- **Reset selection** that means to clean all the pcakges selected for installing/removing
- **Refresh metadata** this should reset cache, but it seems it does nothing in dnfdaemon atm, yumex-dnf behaves the same, we are investigating
- **Repositories** that allows to enable/disable repos, seems not to be permanent though, yumex-dnf behaves the same, it should be another dnfdaemon issue
On master we have an additional Option menu that contains a _user setting_ dialog to manage a couple of requirement asked from yumex user experience
Help menu is just for the About dialog atm. 
I hope this could help

**Comment by anaselli** [comment]
Menus are now cahnged using new libyui-mga implementation see some screenshot [here](https://github.com/manatools/libyui-mga/tree/master/screenshots)
