### ISSUE TITLE
Package list not always updating after selecting a group

### ISSUE THREAD

**Issue by kkofler** [manatools/dnfdragora#4]
Using revision bb6edcf85175a04d9d599ab2754a5e3a6c409ef9 and libyui-qt.

After selecting the first group, I have to click into the package list, then back into the group list to wake it up, then it usually works normally. If I don't do that, if I select another group, the package listing does not update (it still has the first list).

**Comment by kkofler** [comment]
Interestingly, I found that double-clicking works in that case. This is just weird, sometimes single-click works, sometimes not.

**Comment by anaselli** [comment]
yes, i have to investigate on it. I seem to recall i don't have it in
Mageia, but packages <-> groups management are performed differently.

As soon as possible i will give it a try

**Comment by anaselli** [comment]
with the commit 0f087230bd45eaa388e166ef6898ee09fdbe6dfe this issue should be solved. I need to fix the package<->groups problem to show only the involved groups, but that is another issue :)

**Comment by kkofler** [comment]
I think you meant to close #5 instead of this one.

**Comment by anaselli** [comment]
ops sorry :/

**Comment by jamundso** [comment]
Seeing this on Fedora 26. Check/Uncheck an individual package works sometimes as well.

**Comment by anaselli** [comment]
hh @jamundso i haven't experienced anything like that, could you please provide a test case?

**Comment by jamundso** [comment]
dnfdragora-1.0.1-5.git20170505.2a3b056.fc26.noarch

1. Switch left menu to Groups.
2. Click left arrow to expand Base System
3. Click on Hardware Support. The "Hardware Support" packages are displayed to the right.
4. Click on Java. The "Hardware Support" packages **remain** displayed to the right.
5. Click back on Hardware Support.
6. Click to select an available package, e.g. cmospwd, then click again to unselect it.
7. Click on the group Java.
8. The "Java" packages are displayed on the right.

**Comment by anaselli** [comment]
I've made some tests using fedora 32 and software from git [version 2.0.3](https://github.com/manatools/dnfdragora/releases/tag/2.0.3) and it seems to work. I'll close it.
Fill free to open a new bug if you experience any problems. Thanks for reporting it
