### ISSUE TITLE
Recognize and handle the installation of SRPMs 

### ISSUE THREAD

**Issue by xenithorb** [manatools/dnfdragora#43]
Often when I want to hack on a build that I come across I download the SRPM and run `rpm -i <SRPM>` as a normal user. This of course installs the files in the proper build directories in `~/rpmbuild/`. `dnfdragora` seems to have been built with the predisposition that all rpms are to be installed as system packages, because presently it asks for root permissions when I click on an SRPM. 

Expected results:

1. When processing an SRPM with `dnfdragora` (whether clicking on one or otherwise) it should install it as a normal user and have the same effect as `rpm -i`.

**Comment by Conan-Kudo** [comment]
DNF itself doesn't support "installing" source packages. This is a restriction in dnfdragora that we inherit from DNF. Please file a bug with DNF upstream.

**Comment by xenithorb** [comment]
I know but you're supporting the association to *.rpm files, why not handle this anyway?

**Comment by Conan-Kudo** [comment]
Don't get me wrong, I'd like to support it, but dnfdragora is a high-level package manager. If we were to support it, we'd want it to trigger the installation of build dependencies along with installing the source files in the right place. For that to work, DNF needs to support processing source RPMs. It currently does not.
