### ISSUE TITLE
Can't Close Panel Notification

### ISSUE THREAD

**Issue by jimkp** [manatools/dnfdragora#45]
Using on Korora 25 Xfce
dnfdragora.noarch                                           1.0.1-5.git20170505.2a3b056.fc25                                       
dnfdragora-gui.noarch                                       1.0.1-5.git20170505.2a3b056.fc25
After running dnfdragora-updater from the menu an icon appears in the notification area. Right click on that icon gives a few options and all work except the final one "Exit". The icon doesn't disappear and remains active, i.e. the other options continue to work.

**Comment by jimkp** [comment]
Further info on this. I ran the Check Update option and it crashed. Now the exit option is working.

Not sure what was happening before. But will monitor in future. If I can't re-produce in the next couple of days I'll close this.

**Comment by jimkp** [comment]
I've been monitoring this and seeing it happen occasionally. Today I finally worked out what triggered. The panel icon becomes unresponsive after resuming from hibernation. 

As mentioned running Korora 25 Xfce, all latest updates from Fedora including kernel 4.10.15-200.

**Comment by jimkp** [comment]
Additional information -
When trying to run dnfdragora with the icon unresponsive I see this error "nfdaemon client error: g-io-error-quark: GDBus.Error:org.baseurl.DnfSystem.LockedError: dnf is locked by another application (36)"

**Comment by anaselli** [comment]
good catch indeed we don't unlock if we don't exit the program. We should think how to manage something like that @Conan-Kudo wdyt?

**Comment by Conan-Kudo** [comment]
@anaselli Yeah, most definitely. We probably need something to ensure that things hand off smoothly, or otherwise this will remain pretty broken.
