### ISSUE TITLE
[GTK+ GUI] With Adwaita:dark theme, URLs are very hard to read

### ISSUE THREAD

**Issue by genodeftest** [manatools/dnfdragora#47]
Steps to reproduce:
1. switch your Gtk+ theme to Adwaita:dark, e.g. by using `gnome-tweak-tool` or adding the environment variable `GTK_THEME=Adwaita:dark`
2. run dnfdragora (the Gtk+ GUI)
3. have a look at any package info

What happens:
The theme is hard to read. Links look painful. See this screenshot:
![dnfdragora-adwaita-dark](https://cloud.githubusercontent.com/assets/934401/26028024/9cb18b74-3818-11e7-845c-69fadf57bf2b.png)

What should happen:
Links should be lighter.

Installed software versions:
gtk3-3.22.12-2.fc25.x86_64
dnfdragora-1.0.1-5.git20170505.2a3b056.fc25.noarch
libyui-gtk-2.44.9-2.fc25.x86_64

**Comment by anaselli** [comment]
For dnfdragora point of view that is just a link in a Rich Text field, so i don't know why link does not respect theme, do you know if the Qt one has the same effect?
I think this is more a thing to address to [libyui](https://github.com/libyui/libyui) or [libyui-gtk](https://github.com/libyui/libyui-gtk)

**Comment by genodeftest** [comment]
I haven't used (or even had installed) dnfdragora in years and doubt I can provide feedback on this issue.

**Comment by anaselli** [comment]
Thanks for taking time to provide an answer. I'll close it then.
