### ISSUE TITLE
User experience: Improve search and filter

### ISSUE THREAD

**Issue by genodeftest** [manatools/dnfdragora#56]
Note: This issue has been created from #48.

#Steps to reproduce:
1. open dnfdragora (the Gtk+ GUI)
2. use it

# the filter `GtkComboBox`es
The widgets for selecting "All" or "Group", architecture, name:
When one of these comboboxes changes, it will immediately trigger a new search. This disturbes the user workflow since it blocks all UI.

Two possible solutions:
* If you want to have immediate search, please make it non-blocking (this would be the ideal case). In this case, please get rid of the "Search" button.
* If immediate search is too hard to do, please do only trigger search when pressing the search button.

# Installed software versions:
gtk3-3.22.12-2.fc25.x86_64
dnfdragora-1.0.1-5.git20170505.2a3b056.fc25.noarch
libyui-gtk-2.44.9-2.fc25.x86_64

**Comment by anaselli** [comment]
@genodeftest thanks, yes that can be addressed to dnfdragora. TBH it's a design choice to change the view once All or Gorup has been chosen. The "search" is for the text entry only. "All" and "Group" are unrelated, but if you have performed a search the result should be updated into the new view. That is the way it worked in rpmdragora, i just ported the code to python. The bad here, I believe is the group caching time, correct me if I'm wrong, but that is only a Fedora issue and we need to find a way out see also issue #52

**Comment by genodeftest** [comment]
Ok, maybe #52 is all it takes to fix this.
