### ISSUE TITLE
Incorrect install status

### ISSUE THREAD

**Issue by tsoernes** [manatools/dnfdragora#58]
http://i.imgur.com/Qs8rS5c.png

Same happened for pulse audio

Fedora 26 Beta KDE

**Comment by anaselli** [comment]
could you please tell me the steps to arrive there? I mean if you open again is that package installed or not?

**Comment by tsoernes** [comment]
I first had the issue with pulseaudio. Restarted and it appeared correctly as installed. Then afterwards I had the issue with X11. Restarting fixed the issue. Both of them showed as installed now. I have not touched (reinstalled etc) either of the packages. Happened right after clean install of aforementioned distro and subsequent system update.

**Comment by anaselli** [comment]
I think it isn't a matter of packages, just of the reload operation. @Conan-Kudo any changes in dnf there by any chance?

**Comment by anaselli** [comment]
Could you please check with latest code?

**Comment by tsoernes** [comment]
Looks alright now, though I've upgraded to F27 in the meantime
