### ISSUE TITLE
Hide notification in KDE System tray when no updates are available

### ISSUE THREAD

**Issue by CRCinAU** [manatools/dnfdragora#60]
I would love to check for updates on a schedule, but have the tray icon 'hidden' when no updates are available.

KDE has 3 'modes' for system tray icons: Auto, Shown, Hidden.

When no updates are available, the tray icon should be in 'hidden' mode. When an update is available, it should be in 'shown' mode.

This way it becomes obvious when updates are available.

**Comment by smilesbright** [comment]
I would also like this feature please, as well as the option to completely hide the system tray icon. Actually, all applications which make system tray entries should have these kinds of options, even if it's only a command line option. Though being on Cinnamon, it would be nice if this desktop just handled them like KDE apparently does...
