### ISSUE TITLE
[i18n CZ] Wrong translation of "Check all"

### ISSUE THREAD

**Issue by martinky82** [manatools/dnfdragora#61]
https://github.com/manatools/dnfdragora/blob/master/po/cs.po#L1127

The czech translation of "Check all" is wrong (to check can be translated in several meanings, but the one selected does not make any sense). Correct translation shall be "Vybrat vše" (literally select all).

**Comment by yurchor** [comment]
Fixed. Thanks.

**Comment by martinky82** [comment]
That was super quick. Thanks!
