### ISSUE TITLE
Some already translated strings are displayed in English

### ISSUE THREAD

**Issue by kakurasan** [manatools/dnfdragora#64]
Though some strings are already translated, they're displayed in English.

* Command-line options
* Strings in dnfdragora/const.py

Example:
![dnfdragora-translated-text-displayed-in-english](https://user-images.githubusercontent.com/10556453/28970380-48fcfe82-7963-11e7-9e60-01d3ca58360d.png)

The "Installing: ..." (`msgid "Installing: %s"`) is already translated but displayed in English.

**Comment by Conan-Kudo** [comment]
Fixed by merging #65.
