### ISSUE TITLE
Change title from "Software Management" to "Package Management"

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#69]
Hi. 1st I would like to thank you very much for your very hard efforts to evolute dnfdragora. Special thanks for your fix for issue62 (add column size).

Please open attached picture. It is screenshot from my PC.

![screenshot](https://user-images.githubusercontent.com/25375330/30660095-48d187f2-9e2f-11e7-840a-7a22aa95af68.png)

I put 2 markers: red line & blue line pointing on area where appear "Software manager". I think it will be better to change it into "Packages manager", since software managers (in GNOME, Mint, Ubuntu, ...... etc) do not show all packages. While program like symantic or Yum (DNF) Extender, dnfdragora, ..... show all packages.

Best.

**Comment by Conan-Kudo** [comment]
So, the name "Software management" actually comes from dnfdragora's spiritual ancestor: rpmdrake. And you are managing software when you manage packages. Arguably, the software centers are only application stores, rather than full software management systems.

But... @anaselli, what do you think about having the alternate title "Package Management"? I'm not too hot on the idea, but I could be convinced...

**Comment by anaselli** [comment]
dnfdragora is a cross distro package manger, so i have no problem in changing a title that identify it better... moreover if asked by who are using it :)
Changing that needs a translator work also though @yurchor, wdyt about it?

**Comment by papoteur-mga** [comment]
Personally, I am fine Software management, this is what this application does, even if it is trough packages. It is true also that we don't have "Graphical applications" filter as rpmdrake has.

**Comment by Conan-Kudo** [comment]
What would we even use as the qualification for the filter? Check to see if the package has an `application()` Provides?

**Comment by anaselli** [comment]
I haven't any particular opinions either in favour or against :) Software is... software but from dnfdragora point of view software and applications are indeed pacakges, as rpm recalls too...

**Comment by papoteur-mga** [comment]
I don"t know, what I know is that the filter exists in rpmdrake.
It is set by default, thus when a newbie tries to look for a package which is not a GUI application, he/she doesn't find it. This is why we advice all the time to unset this filter.

**Comment by anaselli** [comment]
> I don"t know, what I know is that the filter exists in rpmdrake.
> It is set by default, thus when a newbie tries to look for a package which is not a GUI application, he/she doesn't find it. This is why we advice all the time to unset this filter.

Indeed, that's also a reason why i didn't spend  so much time to understand what GUI packages are and didn't implement it. In future we could improve search button maybe using tags, regex or any other things...

**Comment by anaselli** [comment]
Leaving Software management by now then
