### ISSUE TITLE
Improving arrengment of options inside "User preferences" dialog

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#70]
Hi.

Currently (on my dnfdragora version 1.0.1) on Fedora 26, options inside "User preferences" dialog appearing one beside other like:

"Show updates next startup"  "Do not show groups view next  startup

I suggest on you to make them one under other to avoid confusion. This confusion may be not prominent in case of above example because there are check box before each of above 2 options which assist in recognition of them as 2. But for:

"Proceed without asking for conformation"  ""Interval in minutes to check for updates"

confusion it will be more prominent & possible because no check box before "Interval in minutes to check for update" (it not need such check box off-course). There is no even a vertical separation line between these 2 options. Here it will be useful to put options (ALL options) one bellow other.

This will be more important for users using dark theme (especially when combined with low brightness due to long duty on laptop screen).

![preferances](https://user-images.githubusercontent.com/25375330/30660948-04152c2e-9e32-11e7-8885-ae0a761cc8b3.png)

**Comment by anaselli** [comment]
i haven't really cought your point :( could you please add a fake screenshot even a text prototype showing what you would like to have?

**Comment by Nokia808** [comment]
@anaselli 
Hi. I mean the following: currently we have (one beside other):

"Show updates next startup"      "Do not show groups view next startup"

I suggest to be as one bellow other as following:

"Show updates next startup" 
"Do not show groups view next startup"

Currently we have one beside other:

"Proceed without asking for conformation"      "Interval in minutes to check for updates"

I suggest to be one bellow other as following:

"Proceed without asking for conformation" 
"Interval in minutes to check for updates"

So, we have currently the following arrangement:

"Show updates next startup"      "Do not show groups view next startup"
"Proceed without asking for conformation"     "Interval in minutes to check for updates" 

My suggestion to make these options arranged one bellow other as following:

"Show updates next startup"      
"Do not show groups view next startup"
"Proceed without asking for conformation"      
"Interval in minutes to check for updates" 

I was clear !

Bye the way, what date to release next version of dnfdragora ? I'm very exited to see columns size new option to get relief from layout problem.

Best.

**Comment by anaselli** [comment]
Well i wanted to change that function, but i forgot to do it... so it also remained as you found it. Maybe open a new issue for that so that i can recall it... thanks
