### ISSUE TITLE
[i18n FR] Wrong French translation of Check All

### ISSUE THREAD

**Issue by azriek** [manatools/dnfdragora#73]
https://github.com/manatools/dnfdragora/blob/b3720adc50a9569d79716c9e9ded952ab57e75ae/po/fr.po#L1130

A correct translation would be
  msgstr "Tout coch&er"

Ref: https://fr.wikipedia.org/wiki/Coche_(typographie)

**Comment by yurchor** [comment]
Reported to the Mageia i18n mailing list for the French team consideration.

**Comment by Conan-Kudo** [comment]
@azriek As a note, if you'd like contribute to our translations, they are in our Transifex project: https://www.transifex.com/MageiaLinux/mageia/dnfdragora/

**Comment by yurchor** [comment]
Fixed by this commit: https://github.com/manatools/dnfdragora/commit/129571759a05b35e5f58ff845a7d3ea10a546e08
