### ISSUE TITLE
Reset the selection option doesn't work

### ISSUE THREAD

**Issue by jimkp** [manatools/dnfdragora#74]
As I understand it the option in File - Reset the selection should change the selection criteria to the previous state. However I can't get it to work. If I have searched for something and then choose that option nothing changes in the display.
Tested in Korora 26 with version 1.0.1.

**Comment by anaselli** [comment]
It should clear any actions to packages either addition or removal, so if you select a package to install and then change view to look for another one and reset the selection nothing changes into display but the package you added should be "unchecked", e.g. removed from the _package to install_ list.

**Comment by jimkp** [comment]
Okay, that explains it better than I understood what it was doing. thanks

I'll close this.
