### ISSUE TITLE
dnfdragora "Search" does not recognize "Ring" package !

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#75]
Hi. I'm on Fedora 26 X64 bit Cinnamon edition. I added external repository (repository of "Ring" messenger) as following: 
sudo dnf config-manager --add-repo https://dl.ring.cx/ring-nightly/fedora_27/ring-nightly.repo
sudo dnf install ring
Please see:
https://ring.cx/en/download/gnu-linux

Repository added O.K & I receiving updates ......

But I noticed that this package "ring" not appear in search result of dnfdragora when I searched it !!

Please your kind investigation about this strange phenomenon.

Best.

**Comment by anaselli** [comment]
Do you see that repo into repositories dialog? (Menu File->Repositories)

**Comment by Nokia808** [comment]
Yes, I'm seeing it, the way you asked.

**Comment by anaselli** [comment]
Enabled i guess...
A shot in the dark... have you restarted the system after adding your repo?

**Comment by Nokia808** [comment]
Yes, Ring repository is appearing & being enabled ..... Also, I restarted my OS after adding this repository ......

Please notice the following:
I'm already recognized this issue several months ago when I added Ring repository at that time. However, I did not like to post this bug here because I was think that it is not important. BUT 2 days ago I opened my laptop, then I opened dnfdragora & it show me no new update packages. So, I decided to run:

sudo dnf upgrade --refresh

when the output of this command in terminal show me only 2 packages for update from Ring repository: ring & ring daemon ....... In this case, when "sudo dnf upgrade --refresh", show me new update packages, then when I would re-opened dnfdragora then it should show me these new packages. But here it DID NOT !!! So, I decided to restart my system. Then after restarting my laptop, I waited too to see if dnfdragora updater notify me about these 2 update packages or not. BUT it did not notify me about them ! Here I launched dnfdragora & set at "package to update" BUT it did not show me these 2 packages ..... After that I recognized that the bug is sever & I post bug#75 & bug#76 here.

Best.

**Comment by anaselli** [comment]
ok is a bug, issue #76 though is the same as this one since both updater and dnfdragora uses the same code as backend, e.g. dnf-daemon frontend

**Comment by Conan-Kudo** [comment]
I suspect that dnfdaemon isn't picking up new repositories properly, but I need to test to verify this.

**Comment by Nokia808** [comment]
Is this post enough or I have to file a bug to Redhat BugZilla ?

**Comment by anaselli** [comment]
i installed the repository and ring was there ready to be installed.

**Comment by Nokia808** [comment]
I have to correct: the problem is that "ring" does not appear in search result at TOP ! In fact user have to scroll downward in results too much till see "ring"

see following pictures in sequence (they show scroll from up to down till appear - I make breaf: in fact more that 7
![7](https://user-images.githubusercontent.com/25375330/35005395-279066e4-faeb-11e7-83fe-4e869a831611.png)
![6](https://user-images.githubusercontent.com/25375330/35005397-27c3b38c-faeb-11e7-913f-77f8a88a1396.png)
![5](https://user-images.githubusercontent.com/25375330/35005400-27ee58d0-faeb-11e7-8b69-dd881089b649.png)
![4](https://user-images.githubusercontent.com/25375330/35005402-2819405e-faeb-11e7-86be-483a0ce5895c.png)
![3](https://user-images.githubusercontent.com/25375330/35005403-28443f48-faeb-11e7-9711-e99030c510f3.png)
![2](https://user-images.githubusercontent.com/25375330/35005404-286a5cc8-faeb-11e7-84bb-c9ac5e67e95a.png)
![1](https://user-images.githubusercontent.com/25375330/35005405-2891cf60-faeb-11e7-92e6-db0d219ad50a.png)






 screenshots needed):
