### ISSUE TITLE
dnfdragora updater do not notify about new update from "Ring" repository !

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#76]
Hi. I'm on Fedora 26 X64 bit Cinnamon edition. 

I added external repository of "Ring" messenger:

sudo dnf config-manager --add-repo https://dl.ring.cx/ring-nightly/fedora_27/ring-nightly.repo
sudo dnf install ring
Please see:
https://ring.cx/en/download/gnu-linux

I noticed that dnfdragora do not notify me about new update from this repository, although it do well this for Fedora & RPMFusion repositories !!

Please your kind investigation about this issue.

Best.

**Comment by anaselli** [comment]
as far as i can say dnfdragora shows it as update, what is not working as expected is dnfdragora-update, it seems not to notify the updates (or at least some of them). Check is performed every 180 (minutes iirc) and at start-up. I suspect GetPackage("updates") does not return the updates list correctly.

**Comment by anaselli** [comment]
hmm tested with skypeforlinux and worked, i'll wait for a ring update, but it seems to work to me

**Comment by Nokia808** [comment]
Hi. Again I get update from ring before some days & same error: no notification about ring update (notification from dnfdragora updater).
