### ISSUE TITLE
Support for Sortable Size Column

### ISSUE THREAD

**Issue by mjmg** [manatools/dnfdragora#77]
On the old yum based yumex we had this capability for sorting RPM by size. Please advise if this could be implemented. Thanks.

**Comment by anaselli** [comment]
hmm, honestly should have worked for free... but i've just realized that the sorting method gives an almost funny result :D 
e.g. 12k is less than 10M, but this last is less than 20k... any ideas on how showing those strings to get the right chars order?

**Comment by anaselli** [comment]
btw could you please explain how can i sort column in yumex-dnf i seem i cannot find it...

**Comment by mjmg** [comment]
It was present in the old yum based yumex but was gone in yumex-dnf.
