### ISSUE TITLE
Features/Bug list report with Fedora 27 x64 (xfce)

### ISSUE THREAD

**Issue by didli** [manatools/dnfdragora#79]
_Note : please don't mind this report if bugs and requests mentionned in this report are currently adressed or in the way to be fixed_
Hi everyone !
Here's a few things I've noticed when playing a bit with dnfdragora UI in Fedora 27 xfce x64.
Fedora 27 dnfdragora Issues list :
- Trying to sort (any) column crashes the app, leaving dnf-daemon running in the background (which in turn prevent to run dnfdragora again unless it's killed).
- lost space ^^ : there's a lot of space lost in dnfdragora UI, more apparent in a maximized window. 
http://didli.free.fr/Images/Forums/capture_2017-12-21_20-34-56.jpg      
- When running the UI for the first time in a while, it should mentionned (as progress in the progress bar for example ?) that it's currently checking and refreshing metadata.
Anyway, thank you for dnfdragora !

**Comment by anaselli** [comment]
- With last commits some crashes have been fixed.
- Space will stay there atm, in future who knows
- Metadata progress has to be fixed also in dnfdaemon
Thanks for the report

**Comment by didli** [comment]
Thanks for the update ! For the metadata progress, I think I remember that yumex-dnf was able to display it just fine. Was there a change in dnf-daemon that prevents that now ?

**Comment by anaselli** [comment]
@hellcp point one iirc happens using libyui-gtk i think the problem is in YTable implementation, but could also be only in our YMGA_CBTable, can you check this too?

**Comment by anaselli** [comment]
Removed logo line to gain room, new menubar from libyui-mga and sorting seems to work also for gtk now (new libyui-gtk 2.49.0) 

![immagine](https://user-images.githubusercontent.com/1303486/89713639-4d666000-d999-11ea-81df-17332dae468b.png)
