### ISSUE TITLE
dnfdragora updater do not recognize update from RPMFusion repositories !!!!

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#80]
Hi. 
1st happy new year all !
I'm already opened issue #76 , but I'm discover that not only Ring repositories affected, but other repositories ! Today I received a notification about new update from GNOME software center but dnfdragora show no any notification about this ! So, I decide to run "sudo dnf upgrade --refresh" to see what are the update packages. They was only 2: vlc & vlc-core both from RPMFusion.

After that I restart my laptop to see if dnfdragora notify me about this update or not. It did not notify me at all & after a time interval GNOME software center notify me about update !!

It seem that dnfdragora do not recognize PMFusion also ! I'm afraid that it do not recognize any repositories other than official Fedora repositories !! 

Kindly investigate this issue more. I feel that it is global !

RPMFusion are enabled on my system & appear in dnfdragora GUI as being checked their boxes .......
--------------------------------

Please is there approximate date for new release of dnfdragora ?

**Comment by anaselli** [comment]
as said by reporter this is duplicated of issue #76
