### ISSUE TITLE
dnfdragora-updater crashed when using Papirus-Dark icon theme

### ISSUE THREAD

**Issue by wangxa** [manatools/dnfdragora#82]
The error is 
`
Image.py:2572:open:OSError: cannot identify image file '/usr/share/icons/Papirus-Dark/64x64/categories/dnfdragora.svg'
`
The dnfdragora icon in Papirus-Dark is a symbolic link. But Image.py (provided by Pillow) seems not to support symbolic images.

**Comment by anaselli** [comment]
could you check if using a **png** works instead?

**Comment by wangxa** [comment]
Do you mean the dnfdragora icon is still a symbolic link but the source is a png?

**Comment by anaselli** [comment]
yes please, check if the problem is in file format

**Comment by wangxa** [comment]
If I change the source icon file to a png, then the updater works no matter what the extension name of the symbolic link is: .png or .svg.

**Comment by anaselli** [comment]
ok so the problem seems to be on icon file format, need to check upstream  [libyui ](https://github.com/libyui) for that

**Comment by DarthWound** [comment]
Hello, any news about this?

I have the exact same issue, no updates notification if I use an icon theme like Papirus which uses SVG.

**Comment by anaselli** [comment]
it's an upstream problem i guess, can you open a bug against [libyui](https://github.com/libyui)?

**Comment by gorkoda1** [comment]
> it's an upstream problem i guess, can you open a bug against [libyui](https://github.com/libyui)?

I did some digging and this line of code seems to be the problem
https://github.com/manatools/dnfdragora/blob/7979aed6e59a6c4798b4f140f9e0ce947e2723ef/dnfdragora/updater.py#L66
Python Imaging Library (PIL) [doesn't support svg images](https://stackoverflow.com/questions/3600164/read-svg-file-with-python-pil).

**Comment by Conan-Kudo** [comment]
Is the bug report or something for PIL to consider adding svg support?

**Comment by gorkoda1** [comment]
> Is the bug report or something for PIL to consider adding svg support?

I do not know.

**Comment by anaselli** [comment]
Adding some references to this issue:
- [Pillow supported image files](https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html)
- [Pillow request for supporting SVG files](https://github.com/python-pillow/Pillow/issues/3509)
