### ISSUE TITLE
French translation issues

### ISSUE THREAD

**Issue by jotak** [manatools/dnfdragora#88]
Hi,
There's several translation issues in French:

"Mettre à jour les informations" is a wrong translation from English "Update information": should be "Informations sur la mise à jour".

Also "Requis" should rather be "Prérequis"

"Liste de fichier" should be plural: "Liste des fichiers"
 
Regards

**Comment by yurchor** [comment]
Thanks for the notice.

Reported to our translation mailing list for farther consideration.

**Comment by yurchor** [comment]
Fixed in commit f8a7851

Thanks again for your corrections.
