### ISSUE TITLE
Adding GUI control for type of interface of dnfdragora

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#89]
Hi.

Currently we have following options:

--gtk
--qt
--ncurses

but these can not selected unless from terminal. I suggest on you to make it possible to select type of interface from GUI by adding options for that under "User preferences".

Please the selection of user should be rememberable by dnfdragora

Best.

**Comment by anaselli** [comment]
nope. We cannot decide which ui to use without having all the [libyui](https://github.com/libyui) plugins installed. So that is correct only for a user choice. If you want to use qt instead of gtk, just install libyui-qt plugins and remove gtk ones maybe. While ncurses is anyway a fallback
