### ISSUE TITLE
Make open in full screen rememberable

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#90]
Hi. Currently when I open dnfdragora it will open not in full screen mode. When I click on full screen it will change to full screen O.K But when I closed dnfdragora then re-launched it again, then it will opened at non full screen mode again & I have to repeat changing to full screen each time.

I think you should make selection of user rememberable: if select full screen then it will remain full screen till user change to non full screen. And when user select non full screen then remain non full screen till user change it to full screen.

Best.

**Comment by anaselli** [comment]
please move this request to [libyui](https://github.com/libyui) window size is not something really programmable. 
what you can do though is to run it with "**--fullscreen**" option from command line
