### ISSUE TITLE
Is this O.K or it is a bug in DNF ?!!

### ISSUE THREAD

**Issue by Nokia808** [manatools/dnfdragora#91]
Hi. Sorry for this, but I'm enforced to post here to know if it is a bug in DNF or not before file bug in Redhat bugzilla.

Today I run: 

sudo dnf autoremove

it show the following output:

Last metadata expiration check: 0:04:09 ago on Wed 07 Feb 2018 05:09:45 AM GMT.
Dependencies resolved.
================================================================================
 Package            Arch   Version                          Repository     Size
================================================================================
Removing:
 dnfdragora-updater noarch 1.0.1-9.git20180108.b0e8a66.fc26 @updates       25 k
 python3-pystray    noarch 0.14.3-1.fc26                    @@commandline 244 k
 python3-sh         noarch 1.12.14-1.fc26                   @@commandline 288 k
 python3-xlib       noarch 0.19-2.fc26                      @@commandline 1.1 M

Transaction Summary
================================================================================
Remove  4 Packages

Freed space: 1.7 M
Is this ok [y/N]: N
Operation aborted.

I abort the process because DNF like to remove "dnfdragora-updator" !!

Then I run the following command to know if dnfdragora require dnfdragora-updator or not:

sudo dnf repoquery --requires dnfdragora

the output was:

Last metadata expiration check: 0:12:05 ago on Wed 07 Feb 2018 05:09:45 AM GMT.
/bin/sh
/usr/bin/env
/usr/bin/python3
dnf >= 1.0.9
filesystem
hicolor-icon-theme
libyui-mga-ncurses
python(abi) = 3.6
python3-PyYAML
python3-dnfdaemon
python3-yui >= 1.1.1-10

So, it does not need dnfdragora-updator !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I received 2 updates for dnfdragora several weeks ago. So do you make changes that led to make dnfdragora-updator of no use ? I mean is dnfdragora-updator is useless now & it's previous functionalities now executed dnfdragora package itself ? If yes, so this is not a DNF bug. But if not then I should file a bug for Redhat bugzilla. 

It shouldn't be a bug because 2nd command did not show "dnfdragora-updator" as require but I'm not sure & I like dnfdragora notification function about new update packages availability & I do not like to loss it.

My current dnfdragora version is: 1.0.1, release: 9.git20180108.b0e8a66.fc26

I'm on Fedora 26 X64 bit Cinnamon edition.  

Please your kind help.

**Comment by Conan-Kudo** [comment]
This is related to the downstream packaging of `dnfdragora` in Fedora. There was a bug downstream where the behavior of `Recommends` was not wanted, since not everyone wanted the updater all the time. It was changed to be Obsoletes (installed once), and then considered a fully independent component.

If you want the updater, you'll need to install it yourself. `dnfdragora-updater`.
