### ISSUE TITLE
dnfdragora fails to show changelog of packages

### ISSUE THREAD

**Issue by Woi** [manatools/dnfdragora#92]
### Description of problem:
Dnfdragora fails to show changelog of packages.

### Version-Release number of selected component:
Fedora 26 and Fedora 27
```
$ dnfdragora --version
dnfdragora 
version: 1.0.1
```
```
$ dnf info dnfdragora|grep -e Version -e Release
Version      : 1.0.1
Release      : 9.git20180108.b0e8a66.fc26
```
### How reproducible:
Always

### Steps to Reproduce:
1. Wait till updates are available in the repositories
2. Start dnfdragora
3. Select a package
4. Click on Changelog
5. Recognise "Missing Information" instead of package changelog 

### Actual results:
"Missing Information" is shown instead of actual package changelog

### Expected results:
Package changelog of selected RPM is shown.

### Additional info:
Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1545327

yumex-dnf is able to show package changelog, at least on Fedora 26 (there is no yumex-dnf any more on Fedora 27). See screenshots for details:

![dnfdragora_changelog](https://user-images.githubusercontent.com/5870628/36215567-bede3440-11ac-11e8-953a-1ae722b2a1a4.png)

![yumex-dnf_changelog](https://user-images.githubusercontent.com/5870628/36215568-bf056d1c-11ac-11e8-9ca7-72dd6e422224.png)

**Comment by anaselli** [comment]
Sorry those pictures does not show the same thing. Yumex-dnf does not show changelog either. Upfate information is **not** changelog. To show that you can read [here](https://github.com/timlau/yumex-dnf/issues/4), note that is the fouth issue. 
Changelog is not available, that's why is missing, i can remove that view, but that code is hinerited by rpmdragora and urpmi had changelog instead.

**Comment by Woi** [comment]
Thanks for the lightning fast reply. 
OMG, did I really missed this "Update Information" in dnfdragora since Fedora 27 was released? I'll created an other screenshot for others, that might stumble across this. 

Also I'm a bit confused about the differences between "changelog" and "update information" but couldn't find a good explanation. May I asked you for a link or hint?

**Comment by Woi** [comment]
![dnfdragora_updateinfo](https://user-images.githubusercontent.com/5870628/36218138-c1d84904-11b3-11e8-97cd-e7e30350caf3.png)

**Comment by anaselli** [comment]
Below a rpmdragora screenshot:
![screenshot_20180215_092915](https://user-images.githubusercontent.com/1303486/36247105-02497c90-1233-11e8-99b0-e764489c96ce.png)
