### ISSUE TITLE
Applying selected repositories for being enabled is without effect.

### ISSUE THREAD

**Issue by Ricky-Tigg** [manatools/dnfdragora#98]
**Description of problem:**  Applying selected repositories for being enabled has no effect.

Version-Release number of selected component:  dnfdragora.noarch **1.0.1-9**.git20180108.b0e8a66.fc27

**Steps to Reproduce:**
1. As sudo-user select File -> Repositories; enable a repository  e.g. *update-testing*-named repository- Apply change.
2. Repeat operation as _root_ user.

**Actual results:** 

step 1.  –  No prompt for user's password.  No effect.
step 2.  –  No effect.
step 1., step 2.   –  Check in terminal using command:  `$ dnf -v repolist --all | less`

**Expected results:**  Immediate effect with both users.
**Additional info:**  Tested on _Fedora_ OS.

**Comment by anaselli** [comment]
It works as in yumex-dnf. The repository is enabled only for the (dnfdragora) session and it does not require root access. That does not mean is correct, it just works like so. We are trying to implement something better but that does need to work on dnfdaemon first. I would move this bug there.

**Comment by Ricky-Tigg** [comment]
Unknown expectable behaviour which is no surprise since the output related to entry **Help** -> **Manual**  has remained unchanged as 
> Not implemented yet.

Nevertheless I managed (not found a fix) to get the box checked persistently during the session, by running –here as aliases– the following commands:
`# dnf clean all;rm -rf /var/cache/yum;cat /dev/null > ~/.bash_history && history -c && exit`
`# dnf autoremove -y`
`# dnf distro-sync -y`

Assumed that the state of box checked has the same effect as the one resulting from the execution of the following [command](https://fedoraproject.org/wiki/QA:Updates_Testing?rd=QA/Updates_Testing):
`$ dnf update --enablerepo=updates-testing`

Despite this setting nothing related to the updates-testing repository is updated in Dnfdragora.

Now for testing purpose of the updates-testing repository itself, let's attempt to install winetricks-20180217-1.fc27 which has been pushed to the Fedora 27 testing repository. :

`$ sudo dnf install -y winetricks --enablerepo=updates-testing`
`Last metadata expiration check: 0:48:38 ago on Sun 01 Apr 2018 12:18:28 CEST.`
`Dependencies resolved.`
` Package           Arch          Version                   Repository      Size`
`================================================================================`
`Installing:`
` winetricks        noarch        20171222-1.fc27           updates        170 k`
`Installing dependencies:`
` cabextract        x86_64        1.5-7.fc27                fedora          48 k`

As noticeable installation is unexpectedly not made according to the presently specified repository.

**Comment by anaselli** [comment]
As far as i can say, dnfdaemon enables it for the client session and for the client only i believe, e.g. dnfdragora. We need help to fix and enhance dnfdaemon behavior to manage repositories (adding/removing/enabling/disabling)... and yes for documentation too, volunteers? :)

**Comment by Ricky-Tigg** [comment]
For a scheduled the Finnish documentation project, volunteer I am indeed.

**Comment by Ricky-Tigg** [comment]
Component not for testing yet.

`# dnf install -y dnfdragora --enablerepo=updates-testing`
`Fedora 27 - x86_64 - Test Updates               7.0 MB/s | 3.7 MB     00:00   ` 
`...`
`Package dnfdragora-1.0.1-9.git20180108.b0e8a66.fc27.noarch is already installed, skipping.`
`Dependencies resolved.`
`Nothing to do.`

English speakers speak; others just try, just as I did.

**Comment by Ricky-Tigg** [comment]
OS: _Fedora_ – Installed components:
`$ dnf list installed | egrep 'dnfdaemon|dnfdragora`'
`dnfdaemon.noarch 0.3.18-6.fc28 @fedora`
`dnfdaemon-selinux.noarch 0.3.18-6.fc28 @fedora`
`dnfdragora.noarch 1.0.1-10.git20180108.b0e8a66.fc28`
`python3-dnfdaemon.noarch 0.3.18-6.fc28 @fedora`

Translation –announced to be handled by _Transifex_– is still partially put in action in the interface.

![software management - dnfdragora_001](https://user-images.githubusercontent.com/26058215/40608726-c44228a4-626c-11e8-9cc0-bcd9be1cba87.png)

**Comment by Ricky-Tigg** [comment]
Commented on [1 Apr](https://github.com/manatools/dnfdragora/issues/98#issuecomment-377800330) still stands.

**Comment by anaselli** [comment]
We just fixed this and other issues, we haven't released anything (and either announce) officially. Al you have in fedora is last git snapshot imported, most probably about last December... I see your frustration, but we do our best in our very little spare time...

**Comment by Ricky-Tigg** [comment]
Confusion was not intended. By 'Commented on 1 Apr still stands.' I meant 'volunteer I am' in the context of 'Can you do it for us?'. I would never dare to be frustrated since we –users– are the ones that have to provide help if necessary to the ones –developers– whose tasks matter. I even noticed lately my own error by sending an irrelevant post since version was 1.0.1-10.git20180108.b0e8a66 which is identical for both version 27 and 28 respective repositories. Can you ignore this _[message](https://github.com/manatools/dnfdragora/issues/98#issuecomment-392479404)_.?
