### ISSUE TITLE
DNFDRAGORA Issues

### ISSUE THREAD

**Issue by Brushtail-Highton** [manatools/dnfdragora#99]
I am using dnfdragora on Fedora 27 and having the following issues:

- If I use the search function to get a list of specific packages, it displays the details for the first package in the info window which is fine. If I then click on another package it does not show the details for the clicked package, I have to uncheck/recheck if it is installed or check/uncheck if it is not installed, to see the details. Having done this once clicking on packages in the search results displays the details correctly for the rest of the display of the search results. If I issue another search query the issue repeats itself. This issue occurs every time I use dnfdragora.

- The second issue which for me is a bit more serious, is that when I look at the steam related packages from the negativo17 repository, and attempt to look at the changelog to get the contact details for the maintainer, dnfdragora tells me the change details are missing, but if I do the same thing with yumex it shows the changelog details, so the changelog is actually there.

I have also seen information in an email trail I found on the net that the separator space between the various windows can be narrowed, but I can't find any way of doing this, how is it done?

The version I am using from the Fedora repositories is 1.0.1.

**Comment by anaselli** [comment]
I usually don't like genric title for an issue and a summary that contains too much information not for an issue but for more. It isn't a matter of how much i care of requests of course, but a mess of information. A bug like this does not help me in pointing you things, now and in the future.

Explaining better: for instance your first point has been found thousand times, and it is related to libyui (probably gtk for the most I'm not sure now) but if i look at old issues i don't find my explanations, why? Probably for the same reason, someone wrote a generic issue and mixed all the problems into.
And i'm quite sure i explained changelog one also recently, e.g. changelog metadata in fedora does not exisit while it does in mageia, yumex-dnf (whic code has been ported for such information) showed another thing that is present in other information links.
Last, window separator alrady talked too... libyui is our UI abstraction. To have same layout for different kind of ui libraries (such as, GtK, Qt and ncurses) you necessary have to lose something, better implementation could be sent to [libyui](https://github.com/libyui)
